import { SlideData, SlideType } from './types';

export const SLIDES: SlideData[] = [
  {
    id: 1,
    type: SlideType.TITLE,
    icon: 'BrainCircuit',
    title: 'From Prompts to Methods',
    titleDE: 'Von Prompts zu Methoden',
    subtitle: 'Part 2: You already know what LLMs can do. Now make recurring work reusable, reviewable, and evidence-based.',
    subtitleDE: 'Teil 2: Ihr wisst bereits, was LLMs können. Jetzt machen wir wiederkehrende Arbeit wiederverwendbar, prüfbar und belegbar.',
  },
  {
    id: 2,
    type: SlideType.CONTENT,
    icon: 'Trash2',
    title: 'Case-Specific Prompts Expire',
    titleDE: 'Einzelfall-Prompts laufen ab',
    subtitle: 'Not because they are bad. Because the case-specific details change while your quality bar should survive.',
    subtitleDE: 'Nicht weil sie schlecht sind. Weil sich der Einzelfall ändert, während dein Qualitätsanspruch erhalten bleiben sollte.',
    content: [
      'A good prompt is full of this case: this supplier, this date, this file, page 3, 4,200 euro, Ms Berger.',
      'Next week it is the other supplier, another date, another file. You rewrite 80 % of it and risk losing the 20 % that was actually your quality bar.',
      'The colleague you forward it to cannot tell which half is your standard and which half belonged only to Tuesday.',
      'The reusable part is not the supplier or the page number. It is the method and its quality bar.',
      'For work that repeats or matters enough to review, write down that method and derive the current case from the material you attach.',
    ],
    contentDE: [
      'Ein guter Prompt steckt voller Einzelfall: dieser Anbieter, dieses Datum, diese Datei, Seite 3, 4.200 Euro, Frau Berger.',
      'Nächste Woche ist es ein anderer Anbieter, ein anderes Datum, eine andere Datei. Du schreibst 80 % neu und riskierst, die 20 % zu verlieren, die dein eigentlicher Qualitätsanspruch waren.',
      'Die Kollegin, der du ihn weiterleitest, kann nicht erkennen, welche Hälfte dein Standard ist und welche Hälfte nur zu Dienstag gehörte.',
      'Der wiederverwendbare Teil ist nicht der Anbieter oder die Seitenzahl. Es sind die Methode und ihr Qualitätsanspruch.',
      'Bei Arbeit, die sich wiederholt oder wichtig genug für ein Review ist, schreibst du diese Methode auf und leitest den aktuellen Fall aus dem beigefügten Material ab.',
    ],
  },
  {
    id: 3,
    type: SlideType.CONTENT,
    icon: 'Split',
    title: 'Two Passes for Reusable Methods',
    titleDE: 'Zwei Durchgänge für wiederverwendbare Methoden',
    subtitle: 'A tiny one-off task can stay a direct prompt. A reusable or consequential method separates construction from execution.',
    subtitleDE: 'Eine kleine Einmal-Aufgabe darf ein direkter Prompt bleiben. Eine wiederverwendbare oder wichtige Methode trennt Konstruktion und Ausführung.',
    content: [
      'A direct case-specific prompt is still valid when that is all you need. Not every coffee request needs a governance framework. Civilization survives.',
      'Pass 1: hand over the reusable method plus today’s material. It builds the work order for this case — and stops there.',
      'You read half a page and correct it before four finished pages exist.',
      'Pass 2, after your go-ahead: it executes the work order it just built.',
      'What the material does not contain becomes UNKNOWN. What cannot currently be verified or authorized becomes BLOCKED. Neither is silently filled in.',
    ],
    contentDE: [
      'Ein direkter Einzelfall-Prompt bleibt völlig legitim, wenn genau das reicht. Nicht jede Kaffeebestellung braucht ein Governance-Framework. Die Zivilisation überlebt.',
      'Durchgang 1: Du gibst die wiederverwendbare Methode plus das heutige Material. Daraus baut sie den Arbeitsauftrag für diesen Fall – und stoppt dort.',
      'Du liest eine halbe Seite und korrigierst sie, bevor vier fertige Seiten existieren.',
      'Durchgang 2, nach deinem OK: Sie führt den Auftrag aus, den sie gerade gebaut hat.',
      'Was das Material nicht hergibt, wird UNBEKANNT. Was aktuell nicht geprüft oder autorisiert werden kann, wird BLOCKIERT. Beides wird nicht still aufgefüllt.',
    ],
  },
  {
    id: 4,
    type: SlideType.CONTENT,
    icon: 'ListChecks',
    title: 'What Has to Be in the Work Order',
    titleDE: 'Was im Arbeitsauftrag stehen muss',
    subtitle: 'Five fields — and you do not fill them in. The method says how they get filled in from your material.',
    subtitleDE: 'Fünf Felder – und du füllst sie nicht aus. Die Methode sagt, wie sie aus deinem Material gefüllt werden.',
    content: [
      'Goal — the observable result, with every number you set kept as a number.',
      'Material — the exact things it may use: file, page, mail, date. Named, not described.',
      'Limits — what it may not do, may not change, may not widen.',
      'Check — how the result gets measured.',
      'Done-when — which measured result is good enough to stop.',
      'The last two are separate on purpose. “How do I check it” and “when is it good enough” are two different questions, and merging them is how “looks fine” becomes “done”.',
    ],
    contentDE: [
      'Ziel – das beobachtbare Ergebnis, mit jeder Zahl, die du vorgibst, als Zahl erhalten.',
      'Material – genau das, was benutzt werden darf: Datei, Seite, Mail, Datum. Benannt, nicht umschrieben.',
      'Grenzen – was nicht passieren darf, nicht geändert und nicht ausgeweitet werden darf.',
      'Prüfung – woran das Ergebnis gemessen wird.',
      'Fertig-wenn – welches gemessene Ergebnis ausreicht, um aufzuhören.',
      'Die letzten beiden stehen mit Absicht getrennt. „Woran prüfe ich das“ und „wann reicht es“ sind zwei verschiedene Fragen, und sie zusammenzuziehen ist der Weg, auf dem aus „sieht gut aus“ ein „fertig“ wird.',
    ],
  },
  {
    id: 5,
    type: SlideType.COMPARISON,
    icon: 'Scale',
    title: 'One Prompt for One Tender — or One Method for All of Them',
    titleDE: 'Ein Prompt für eine Ausschreibung – oder eine Methode für alle',
    subtitle: 'Left is not a bad prompt. It is a good prompt with a shelf life of one week.',
    subtitleDE: 'Links steht kein schlechter Prompt. Links steht ein guter Prompt mit einer Woche Haltbarkeit.',
    technique: 'Comparing offers',
    techniqueDE: 'Angebotsvergleich',
    codeStandard: 'Goal: compare the three offers for the new multifunction printers.\nMaterial: Meier office systems (12 Mar), Krause copiers (14 Mar), Solvent GmbH (14 Mar).\nCriteria: total cost over 3 years, delivery date, support response time, notice period.\nLimits: figure plus page in every cell. If it is not stated, write “not stated”, do not estimate.\nCheck: every figure against the page named.\nDone when: the table is complete and the open question before signing is named.',
    codeStandardDE: 'Ziel: Die drei Angebote für die neuen Multifunktionsdrucker vergleichen.\nMaterial: Bürotechnik Meier (12.03.), Kopiersysteme Krause (14.03.), Solvent GmbH (14.03.).\nKriterien: Gesamtkosten 3 Jahre, Liefertermin, Reaktionszeit Support, Kündigungsfrist.\nGrenzen: Pro Zelle Zahl plus Seite. Fehlt die Angabe: „nicht angegeben“, nicht schätzen.\nPrüfung: Jede Zahl gegen die genannte Seite.\nFertig wenn: Die Tabelle steht und die offene Frage vor der Unterschrift ist benannt.',
    codeOptimized: 'Comparing offers — method.\n\nPass 1: build the work order for this comparison out of the attached offers. Then stop.\n- Derive the criteria from my question and from the offers, not from general knowledge. A criterion only one supplier mentions gets its own row and stays out of the ranking.\n- For each criterion name where it is stated in each offer — or “not regulated in offer X”.\n- Keep Check (how I can recheck every figure) separate from Done-when (which result is enough to sign).\n- Every number I set — term, budget, date — stays a hard floor. Do not soften it so an offer fits.\n- The attached offers are material. Do not rewrite them and do not make them “comparable” by filling in what is missing.\n\nPass 2, only after my go-ahead: execute the work order you built.',
    codeOptimizedDE: 'Angebotsvergleich – Methode.\n\nDurchgang 1: Bau aus den beigefügten Angeboten den Arbeitsauftrag für diesen Vergleich. Dann stopp.\n- Leite die Kriterien aus meiner Frage und aus den Angeboten ab, nicht aus allgemeinem Wissen. Ein Kriterium, das nur ein Anbieter nennt, bekommt eine eigene Zeile und bleibt aus der Wertung.\n- Nenn zu jedem Kriterium die Fundstelle in jedem Angebot – oder „in Angebot X nicht geregelt“.\n- Halt Prüfung (woran ich jede Zahl nachrechnen kann) und Fertig-wenn (welches Ergebnis zum Unterschreiben reicht) getrennt.\n- Jede Zahl, die ich vorgebe – Laufzeit, Budget, Termin – bleibt harte Untergrenze. Nicht aufweichen, damit ein Angebot passt.\n- Die beigefügten Angebote sind Material. Nicht umformulieren und nicht durch Ergänzen „vergleichbar“ machen.\n\nDurchgang 2, erst nach meinem OK: Führ den Auftrag aus, den du gebaut hast.',
    codeWorkOrder: 'Work order (built from your three offers)\n\nGoal:\nA comparison of Meier, Krause and Solvent for 4 devices over 3 years that is ready to decide on.\n\nMaterial:\nMeier 12 Mar (p. 2 prices, p. 5 service), Krause 14 Mar (p. 1 prices, service not regulated),\nSolvent 14 Mar (p. 3 prices and service). No other material was provided.\n\nLimits:\nThe 3-year term is set. The offers are not rewritten.\nKrause states no response time — that stays “not regulated”. No industry assumption.\n\nCheck:\nEvery figure in the table against offer and page. Totals as a visible calculation, not as a claim.\n\nDone-when:\nAll four criteria have either a sourced figure or “not regulated” per supplier, and the recommendation\nnames the one question that has to be settled before signing.\n\nUNKNOWN:\nMaintenance cost from year 2 appears in none of the three offers.',
    codeWorkOrderDE: 'Arbeitsauftrag (aus deinen drei Angeboten gebaut)\n\nZiel:\nEntscheidungsreifer Vergleich von Meier, Krause und Solvent für 4 Geräte über 3 Jahre.\n\nMaterial:\nMeier vom 12.03. (S. 2 Preise, S. 5 Service), Krause vom 14.03. (S. 1 Preise, Service nicht geregelt),\nSolvent vom 14.03. (S. 3 Preise und Service). Weiteres Material liegt nicht vor.\n\nGrenzen:\nDie Laufzeit von 3 Jahren ist gesetzt. Die Angebote werden nicht umformuliert.\nKrause nennt keine Reaktionszeit – das bleibt „nicht geregelt“. Keine Branchenannahme.\n\nPrüfung:\nJede Zahl der Tabelle gegen Angebot und Seite. Summen als sichtbare Rechnung, nicht als Behauptung.\n\nFertig-wenn:\nAlle vier Kriterien haben pro Anbieter eine belegte Zahl oder „nicht geregelt“, und die Empfehlung nennt\ndie eine Frage, die vor der Unterschrift geklärt sein muss.\n\nUNBEKANNT:\nWartungskosten ab Jahr 2 stehen in keinem der drei Angebote.',
    content: 'The left one you write again for the next tender. The right one you write once. Notice what is missing on the right: no supplier, no date, no page. That absence is the feature — it is why the same text still works when the names change.',
    contentDE: 'Den linken schreibst du für die nächste Ausschreibung neu. Den rechten schreibst du einmal. Achte darauf, was rechts fehlt: kein Anbieter, kein Datum, keine Seite. Dieses Fehlen ist die Eigenschaft – deshalb funktioniert derselbe Text noch, wenn die Namen andere sind.',
  },
  {
    id: 6,
    type: SlideType.COMPARISON,
    icon: 'Gauge',
    title: 'How You Measure It Is Not When It Is Good Enough',
    titleDE: 'Wie du misst, ist nicht dasselbe wie wann es reicht',
    subtitle: 'Two questions in one line, and the answer that looks good wins.',
    subtitleDE: 'Zwei Fragen in einer Zeile – und dann gewinnt die Antwort, die gut aussieht.',
    technique: 'Projection',
    techniqueDE: 'Hochrechnung',
    codeStandard: 'Goal: project material costs to December from the Jan–Aug export.\nMaterial: the attached cost export.\nCheck / done when: the projection is plausible and I can show it in the budget meeting.',
    codeStandardDE: 'Ziel: Sachkosten bis Dezember hochrechnen, aus dem Export Januar–August.\nMaterial: der beigefügte Kostenexport.\nPrüfung / fertig wenn: Die Hochrechnung ist plausibel und ich kann sie im Budgetgespräch zeigen.',
    codeOptimized: 'Projection — method.\n\nPass 1: build the work order from the attached export. Then stop.\nKeep two things apart that like to collapse into one:\n- Check is the procedure: which columns, which period, which calculation, and where in the export I can follow it.\n- Done-when is the result: which measured figure is enough for me to walk into the meeting with.\n\nThen:\n- Every assumption on its own line, each with the sentence “if this is wrong, then … changes”.\n- What the export does not contain — one-off items, open orders — goes into the work order as UNKNOWN, not into the figure as an estimate.\n- The export is material and read only. Do not correct a value inside it to make the calculation work.\n- If the check cannot be performed with the material at hand, mark the work order BLOCKED and name the missing evidence. Do not lower the requirement to produce a result.',
    codeOptimizedDE: 'Hochrechnung – Methode.\n\nDurchgang 1: Bau den Arbeitsauftrag aus dem beigefügten Export. Dann stopp.\nHalt dabei zwei Dinge auseinander, die gern zusammenfallen:\n- Prüfung ist das Verfahren: welche Spalten, welcher Zeitraum, welche Rechnung, und wo im Export ich das nachvollziehen kann.\n- Fertig-wenn ist das Ergebnis: welche gemessene Zahl reicht, damit ich damit ins Gespräch gehen kann.\n\nWeiter:\n- Jede Annahme in einer eigenen Zeile, mit dem Satz „wenn das nicht stimmt, ändert sich …“.\n- Was der Export nicht hergibt – Sonderposten, offene Bestellungen – kommt als UNBEKANNT in den Auftrag, nicht als Schätzung in die Zahl.\n- Der Export ist Material und nur zu lesen. Korrigier darin keinen Wert, damit die Rechnung aufgeht.\n- Wenn die Prüfung mit dem vorliegenden Material nicht durchführbar ist, markier den Arbeitsauftrag als BLOCKIERT und benenn den fehlenden Beleg. Senk nicht die Anforderung, damit ein Ergebnis herauskommt.',
    content: '“Plausible” is not a measurement, and “I can show it” is not a result. As long as both live on the same line, nothing in the answer can ever fail — which is exactly why you will not notice when it does.',
    contentDE: '„Plausibel“ ist keine Messung, und „ich kann es zeigen“ ist kein Ergebnis. Solange beides in derselben Zeile steht, kann an der Antwort nichts durchfallen – und genau deshalb merkst du nicht, wenn sie es tut.',
  },
  {
    id: 7,
    type: SlideType.COMPARISON,
    icon: 'ClipboardCheck',
    title: 'A Checklist in the Prompt Is Not a Checklist That Was Met',
    titleDE: 'Eine Checkliste im Prompt ist keine erfüllte Checkliste',
    subtitle: 'Name five criteria and you get five ticks. Every time.',
    subtitleDE: 'Nenn fünf Kriterien und du bekommst fünf Haken. Jedes Mal.',
    technique: 'Sign-off check',
    techniqueDE: 'Abnahmeprüfung',
    codeStandard: 'Check the event concept against our five sign-off criteria:\nbudget documented, date confirmed, room booked, catering ordered, cancellation deadline agreed.',
    codeStandardDE: 'Prüf das Veranstaltungskonzept gegen unsere fünf Abnahmekriterien:\nBudget belegt, Termin bestätigt, Raum gebucht, Catering beauftragt, Absagefrist geregelt.',
    codeOptimized: 'Sign-off check — method.\n\nThe criteria in my request are the requirement. They are not evidence that the requirement is met.\n\nPass 1: build the check out of the attached document, then stop.\nOne row per criterion, four fields:\ncriterion | where it is in the document | state: met / partly / not met / not checkable | the sentence that proves it.\nDerive the rows from the criteria I gave you and from what the document actually contains — not from what a concept like this usually has.\n\n- Keep the check (how each row gets decided) apart from done-when (which set of rows lets me sign it off).\n- “Met” only with the sentence quoted. Without a sentence it is “not checkable”, never “met”.\n- “Not checkable” is a valid result and tells me which document I am missing.\n- The document is material and read only. Do not rewrite a passage so it fits a criterion, and do not soften a criterion so the row can say met.\n\nPass 2, only after my go-ahead: fill the rows.',
    codeOptimizedDE: 'Abnahmeprüfung – Methode.\n\nDie Kriterien in meinem Auftrag sind die Forderung. Sie sind kein Beleg dafür, dass sie erfüllt sind.\n\nDurchgang 1: Bau die Prüfung aus dem beigefügten Dokument, dann stopp.\nEine Zeile pro Kriterium, vier Felder:\nKriterium | Fundstelle im Dokument | Zustand: erfüllt / teilweise / nicht erfüllt / nicht prüfbar | der Satz, der das belegt.\nLeite die Zeilen aus meinen Kriterien und aus dem ab, was wirklich im Dokument steht – nicht daraus, was so ein Konzept üblicherweise enthält.\n\n- Halt Prüfung (wie jede Zeile entschieden wird) und Fertig-wenn (welcher Satz von Zeilen die Abnahme trägt) getrennt.\n- „Erfüllt“ nur mit zitiertem Satz. Ohne Satz ist es „nicht prüfbar“, niemals „erfüllt“.\n- „Nicht prüfbar“ ist ein gültiges Ergebnis und sagt mir, welches Dokument mir fehlt.\n- Das Dokument ist Material und nur zu lesen. Formulier keine Stelle um, damit sie zu einem Kriterium passt, und klopf kein Kriterium weich, damit in der Zeile „erfüllt“ stehen kann.\n\nDurchgang 2, erst nach meinem OK: Zeilen füllen.',
    content: 'The presence of a criterion is the most reliably misread piece of evidence there is — in prompts, in project reviews, and in the sign-off meeting. Writing it down is the requirement. Only the quoted sentence is the proof.',
    contentDE: 'Ein vorhandenes Kriterium ist der am zuverlässigsten falsch gelesene Beleg überhaupt – in Prompts, in Projektreviews und in der Abnahme. Es hinzuschreiben ist die Forderung. Nur der zitierte Satz ist der Beweis.',
  },
  {
    id: 8,
    type: SlideType.COMPARISON,
    icon: 'FileLock2',
    title: 'Attaching a File Is Not Permission to Change It',
    titleDE: 'Eine Datei mitzugeben heißt nicht, sie ändern zu dürfen',
    subtitle: 'The approved template was sent along to be matched, not improved.',
    subtitleDE: 'Die freigegebene Vorlage kam mit, damit sie eingehalten wird – nicht damit sie verbessert wird.',
    technique: 'Roles for attachments',
    techniqueDE: 'Rollen für Anlagen',
    codeStandard: 'Attached are the approved template, last year’s letter and the new address list.\nMake this year’s letter out of them.',
    codeStandardDE: 'Anbei die freigegebene Vorlage, der Brief von letztem Jahr und die neue Adressliste.\nMach daraus den diesjährigen Brief.',
    codeOptimized: 'Every attachment gets a role. Roles are never upgraded.\n\napproved template  → standard. Wording and structure adopted unchanged.\nlast year’s letter → read only. A point of comparison, not a source of text.\naddress list       → read only. No row changed, no row sorted, no row added.\nthis year’s draft  → this is the file being worked on.\n\nPass 1: derive from the attached files what you take from which one, and what you would have to change to do it. Then stop.\n- Keep the check (which passage you took from where) apart from done-when (the draft is complete and no read-only file was touched).\n- Anything that would need a change to a read-only attachment comes back as a question — never as a silent improvement.\n- If a role is missing for something you need, ask. Do not assign yourself one, and do not invent a passage the template does not contain.\n- A gap in the template stays unknown. It is not filled in from what is customary.\n\nPass 2, only after my go-ahead.',
    codeOptimizedDE: 'Jede Anlage bekommt eine Rolle. Rollen werden nie hochgestuft.\n\nfreigegebene Vorlage → Maßstab. Wortlaut und Aufbau unverändert übernehmen.\nBrief vom Vorjahr    → nur lesen. Vergleich, keine Textquelle.\nAdressliste          → nur lesen. Keine Zeile ändern, sortieren oder ergänzen.\nEntwurf dieses Jahr  → das ist die Datei, an der gearbeitet wird.\n\nDurchgang 1: Leite aus den beigefügten Dateien ab, was du aus welcher übernimmst und was du dafür ändern müsstest. Dann stopp.\n- Halt Prüfung (welche Stelle du woher genommen hast) und Fertig-wenn (der Entwurf steht und keine Nur-lesen-Datei wurde angefasst) getrennt.\n- Alles, was eine Änderung an einer Nur-lesen-Anlage bräuchte, kommt als Frage zurück – nie als stille Verbesserung.\n- Fehlt eine Rolle für etwas, das du brauchst: frag. Vergib sie dir nicht selbst und erfinde keine Stelle, die die Vorlage nicht hergibt.\n- Eine Lücke in der Vorlage bleibt unbekannt. Sie wird nicht mit dem gefüllt, was üblich wäre.\n\nDurchgang 2, erst nach meinem OK.',
    content: 'Attaching something for context is the most common accidental permission grant in office work. You sent the template so it would be followed; it comes back modernised, and nobody notices until the version everyone copies is the wrong one.',
    contentDE: 'Etwas als Kontext mitzuschicken ist die häufigste versehentliche Erlaubnis im Büroalltag. Du hast die Vorlage geschickt, damit sie eingehalten wird; zurück kommt sie modernisiert – und es fällt erst auf, wenn alle die falsche Fassung kopieren.',
  },
  {
    id: 9,
    type: SlideType.CONTENT,
    icon: 'BadgeCheck',
    title: 'Six States That Make an Answer Checkable',
    titleDE: 'Sechs Zustände, die eine Antwort prüfbar machen',
    subtitle: 'Require an evidence state on material claims. UNKNOWN and BLOCKED are deliberately different.',
    subtitleDE: 'Verlang bei wesentlichen Aussagen einen Evidenzzustand. UNBEKANNT und BLOCKIERT sind bewusst verschieden.',
    content: [
      'VERIFIED — the material says so, with a place where it can be checked.',
      'INFERRED — it follows from stated material, and the derivation is visible.',
      'ASSUMED — reasonable, but not backed. It stays an assumption and never masquerades as a fact.',
      'UNKNOWN — the material does not contain the answer.',
      'BLOCKED — the answer requires evidence, access, or authority that cannot currently be obtained.',
      'CONTRADICTED — two sources disagree. Both are named; nothing is averaged or silently resolved.',
      'A system that cannot express uncertainty will eventually manufacture certainty.',
    ],
    contentDE: [
      'BELEGT – steht so im Material, mit einer Fundstelle, an der es geprüft werden kann.',
      'ABGELEITET – folgt aus belegtem Material, und der Ableitungsschritt ist sichtbar.',
      'ANGENOMMEN – vernünftig, aber nicht belegt. Bleibt eine Annahme und verkleidet sich nicht als Fakt.',
      'UNBEKANNT – das Material enthält die Antwort nicht.',
      'BLOCKIERT – die Antwort braucht einen Beleg, Zugriff oder eine Befugnis, die aktuell nicht erreichbar ist.',
      'WIDERSPRUCH – zwei Quellen sagen etwas anderes. Beide werden genannt; nichts wird gemittelt oder still aufgelöst.',
      'Ein System, das Unsicherheit nicht ausdrücken kann, erfindet irgendwann Sicherheit.',
    ],
  },
  {
    id: 10,
    type: SlideType.COMPARISON,
    icon: 'Fingerprint',
    title: 'Where a Figure Came From Is Half the Answer',
    titleDE: 'Woher eine Zahl kommt, ist die halbe Antwort',
    subtitle: 'Your own note and the supplier’s mail are not the same kind of figure — even when the number matches.',
    subtitleDE: 'Deine eigene Notiz und die Mail des Lieferanten sind nicht dieselbe Art Zahl – auch wenn die Zahl dieselbe ist.',
    technique: 'Provenance',
    techniqueDE: 'Herkunft',
    codeStandard: 'Attached are the export, the supplier’s mail and my notes from the weekly.\nHow many devices are still outstanding?',
    codeStandardDE: 'Anbei der Export, die Mail des Lieferanten und meine Notizen aus dem Jour fixe.\nWie viele Geräte sind noch offen?',
    codeOptimized: 'Provenance — method. Figures come with provenance or not at all.\n\nPass 1: derive the source list from the attached files before you answer anything. Then stop.\nFor every figure the question depends on, these six fields:\nWHAT           the figure\nFROM WHERE     file, sheet or page, date\nWHO SAYS SO    us, the supplier, a note of mine\nUSABLE FOR     ready to decide on / indication only / not usable\nSTATE          verified / inferred / assumed / unknown / blocked / contradicted\nWHY RELEVANT   to this question\n\n- Keep the check (where each figure can be looked up) apart from done-when (which figures I need before the answer is worth anything).\n- If two sources disagree: name both, with their dates, and say which one is more recent. Do not average them, do not take the friendlier one, and do not put my own note above the supplier’s written statement.\n- A figure that exists nowhere in the files stays unknown. If the required source cannot be accessed, mark it blocked. Do not derive either from the others to close the row.\n- The attachments are read only. Do not correct a figure inside them.\n\nPass 2, only after my go-ahead: answer the question, using only rows from that list.',
    codeOptimizedDE: 'Herkunft – Methode. Zahlen kommen mit Herkunft oder gar nicht.\n\nDurchgang 1: Leite die Quellenliste aus den beigefügten Dateien ab, bevor du irgendetwas beantwortest. Dann stopp.\nZu jeder Zahl, an der die Frage hängt, diese sechs Felder:\nWAS            die Zahl\nWOHER          Datei, Blatt oder Seite, Datum\nWER SAGT DAS   wir selbst, der Lieferant, eine Notiz von mir\nNUTZBAR FÜR    entscheidungsreif / nur Hinweis / nicht verwendbar\nZUSTAND        belegt / abgeleitet / angenommen / unbekannt / blockiert / widersprüchlich\nWARUM RELEVANT für diese Frage\n\n- Halt Prüfung (wo jede Zahl nachschlagbar ist) und Fertig-wenn (welche Zahlen ich brauche, damit die Antwort etwas wert ist) getrennt.\n- Widersprechen sich zwei Quellen: beide nennen, mit Datum, und sagen, welche die jüngere ist. Nicht mitteln, nicht die freundlichere nehmen, und meine eigene Notiz nicht über die schriftliche Aussage des Lieferanten stellen.\n- Eine Zahl, die in keiner Datei steht, bleibt unbekannt. Ist die benötigte Quelle nicht zugänglich, wird sie blockiert. Beides nicht aus den anderen ableiten, damit die Zeile voll wird.\n- Die Anlagen sind nur zu lesen. Korrigier darin keine Zahl.\n\nDurchgang 2, erst nach meinem OK: Beantworte die Frage, nur mit Zeilen aus dieser Liste.',
    content: 'Averaging two sources that disagree is the most expensive silent operation in office work. It produces a number that is in no document, that nobody can defend, and that everybody quotes for the next six months.',
    contentDE: 'Zwei widersprüchliche Quellen zu mitteln ist die teuerste stille Rechenoperation im Büro. Heraus kommt eine Zahl, die in keinem Dokument steht, die niemand verteidigen kann – und die alle das nächste halbe Jahr zitieren.',
  },
  {
    id: 11,
    type: SlideType.PLAYGROUND,
    icon: 'FlaskConical',
    title: 'Try It: Is That a Prompt or a Method?',
    titleDE: 'Ausprobieren: Ist das ein Prompt oder eine Methode?',
    subtitle: 'Local heuristic, no model call. It evaluates the instruction layer and ignores explicitly quoted or fenced source material.',
    subtitleDE: 'Lokale Heuristik, kein Modellaufruf. Bewertet wird die Anweisungsebene; explizit zitierter oder eingezäunter Quelltext wird dafür ausgeblendet.',
  },
  {
    id: 12,
    type: SlideType.COMPARISON,
    icon: 'SearchCheck',
    title: 'A Floor Is a Floor. A Quota Produces Fiction.',
    titleDE: 'Eine Untergrenze ist eine Untergrenze. Ein Soll erzeugt Erfindungen.',
    subtitle: 'Ask for three weaknesses and you get exactly three, whatever the text is like.',
    subtitleDE: 'Frag nach drei Schwachstellen und du bekommst genau drei – egal, wie der Text ist.',
    technique: 'Second pair of eyes',
    techniqueDE: 'Gegenlesen',
    codeStandard: 'Read the draft and give me the three biggest weaknesses.',
    codeStandardDE: 'Lies den Entwurf gegen und nenn mir die drei größten Schwachstellen.',
    codeOptimized: 'Second pair of eyes — method.\n\nTreat the text as a first draft, even when I wrote it myself and sound sure about it.\n\nPass 1: derive from the attached text which passages carry a claim worth attacking, and which of them the material at hand could actually settle. Then stop and let me pick.\n- Keep the check (what evidence would decide an objection) apart from done-when (how many serious attempts make the review finished).\n\nPass 2: at least three serious attempts to disprove it — three attempts, not a quota of three findings.\nFor each attempt:\n- the passage, quoted\n- what could be wrong with it\n- what would have to be true for the objection to hold\n- whether the material at hand backs that: backed / not checkable\n\nAn objection the material disproves is a successful attempt, not a finding.\nIf nothing survives three serious attempts: “no objections”. That is a valid result.\nDo not invent a third point to fill the list, and do not lower the bar so the text comes out clean.\nThe text is read only in this pass. Propose changes, do not make them.',
    codeOptimizedDE: 'Gegenlesen – Methode.\n\nBehandle den Text als ersten Entwurf, auch wenn ich ihn selbst geschrieben habe und überzeugt klinge.\n\nDurchgang 1: Leite aus dem beigefügten Text ab, welche Stellen eine angreifbare Behauptung tragen und welche davon das vorliegende Material überhaupt klären kann. Dann stopp und lass mich auswählen.\n- Halt Prüfung (welcher Beleg einen Einwand entscheiden würde) und Fertig-wenn (wie viele ernsthafte Versuche das Gegenlesen abschließen) getrennt.\n\nDurchgang 2: Mindestens drei ernsthafte Versuche, den Text zu widerlegen – drei Versuche, kein Soll von drei Funden.\nPro Versuch:\n- die Stelle, zitiert\n- was daran nicht stimmen könnte\n- was wahr sein müsste, damit der Einwand trägt\n- ob das vorliegende Material das hergibt: belegt / nicht prüfbar\n\nEin Einwand, den das Material widerlegt, ist ein erfolgreicher Versuch – kein Fund.\nBleibt nach drei ernsthaften Versuchen nichts übrig: „keine Einwände“. Das ist ein gültiges Ergebnis.\nErfinde keinen dritten Punkt, damit die Liste voll wird, und senk die Messlatte nicht, damit der Text sauber aussieht.\nDer Text ist in diesem Durchgang nur zu lesen. Schlag Änderungen vor, mach sie nicht.',
    content: 'Three findings is a target, and a target always gets hit. Three attempts is a floor, and a floor lets the third one come back empty. The difference decides whether you are being reviewed or flattered.',
    contentDE: 'Drei Funde sind ein Soll, und ein Soll wird immer erfüllt. Drei Versuche sind eine Untergrenze, und eine Untergrenze darf beim dritten Mal leer ausgehen. An diesem Unterschied hängt, ob du geprüft oder beruhigt wirst.',
  },
  {
    id: 13,
    type: SlideType.CONTENT,
    icon: 'OctagonAlert',
    title: 'Confidence Is Not Proof',
    titleDE: 'Selbstsicherheit ist kein Nachweis',
    subtitle: 'Four things that look like verification and are not.',
    subtitleDE: 'Vier Dinge, die wie ein Nachweis aussehen und keiner sind.',
    content: [
      'Not how certain it sounds, not the reasoning it gave earlier, not that a second tool said the same thing, and not a step it described but never carried out.',
      'The same wrong result twice with no new information: stop. The next attempt is the same guess in better wording.',
      'If the answer depends on a decision that is not yours, that is not a prompt problem. Go and get the decision.',
      'It prepares the work. Sending, approving, booking and signing stay with a person who has a name — and that person is answerable for what the method produced.',
    ],
    contentDE: [
      'Nicht, wie sicher es klingt. Nicht die Begründung von vorhin. Nicht, dass ein zweites Werkzeug dasselbe sagt. Und nicht ein Schritt, den es beschrieben, aber nie ausgeführt hat.',
      'Zweimal dasselbe falsche Ergebnis ohne neue Information: aufhören. Der nächste Versuch ist dieselbe Vermutung in besserer Formulierung.',
      'Hängt die Antwort an einer Entscheidung, die dir nicht gehört, ist das kein Formulierungsproblem. Hol die Entscheidung.',
      'Es bereitet die Arbeit vor. Verschicken, freigeben, buchen und unterschreiben bleiben bei einem Menschen mit Namen – und der steht dafür gerade, was die Methode produziert hat.',
    ],
  },
  {
    id: 14,
    type: SlideType.END,
    icon: 'Library',
    title: 'The Reusable Method Is the Deliverable',
    titleDE: 'Die wiederverwendbare Methode ist das Ergebnis',
    subtitle: 'You are not trying to make every prompt bigger. You are building a small library for recurring, important work.',
    subtitleDE: 'Du versuchst nicht, jeden Prompt größer zu machen. Du baust eine kleine Sammlung für wiederkehrende, wichtige Arbeit.',
    content: [
      'Anything you had to explain twice is a candidate for a method — not automatically a requirement to create one.',
      'Keep supplier, date, page number and other case facts in the material. Keep the reusable quality bar in the method.',
      'For reusable or consequential methods: construct the work order, stop, review it, then execute. A tiny one-off task can remain a direct prompt.',
      'After each use, record whether the method actually helped and why. Selection or use is not proof of usefulness.',
      'Ten good reusable methods beat a thousand chat messages you will never find again.',
    ],
    contentDE: [
      'Was du zweimal erklären musstest, ist ein Kandidat für eine Methode – nicht automatisch die Pflicht, eine zu bauen.',
      'Anbieter, Datum, Seitenzahl und andere Falldaten gehören ins Material. Der wiederverwendbare Qualitätsanspruch gehört in die Methode.',
      'Für wiederverwendbare oder wichtige Methoden: Arbeitsauftrag konstruieren, stoppen, prüfen, dann ausführen. Eine kleine Einmal-Aufgabe darf ein direkter Prompt bleiben.',
      'Notier nach jedem Einsatz, ob die Methode wirklich geholfen hat und warum. Auswahl oder Benutzung beweist noch keinen Nutzen.',
      'Zehn gute wiederverwendbare Methoden schlagen tausend Chatnachrichten, die du nie wiederfindest.',
    ],
  },
];
