import { GuideMode, SlideData, SlideType } from './types';

/**
 * Deck A: the everyday desk work most people actually do — mails, minutes,
 * long documents, rejections, lists, drafts that somebody will pick apart.
 */
export const DESK_SLIDES: SlideData[] = [
  {
    id: 1,
    type: SlideType.TITLE,
    icon: 'BrainCircuit',
    title: 'Prompting for Everyday Office Work',
    titleDE: 'Prompting im Büroalltag',
    subtitle: 'How to turn a fast, confident colleague who has never seen your files into someone useful.',
    subtitleDE: 'Wie aus einem schnellen, selbstbewussten Kollegen, der eure Unterlagen nie gesehen hat, jemand Brauchbares wird.',
  },
  {
    id: 2,
    type: SlideType.CONTENT,
    icon: 'AlertTriangle',
    title: 'Fast, Fluent, and It Has Never Seen Your Files',
    titleDE: 'Schnell, wortgewandt – und hat eure Unterlagen nie gesehen',
    subtitle: 'Before any tricks: what the thing actually is.',
    subtitleDE: 'Vor allen Tricks: was das Ding eigentlich ist.',
    content: [
      'It is genuinely good at rewriting, shortening, structuring, translating, and getting something onto an empty page.',
      'It has never seen your contract, your customer, your spreadsheet, or Tuesday’s meeting — unless you paste it in.',
      'It does not really calculate. It writes the number that sounds right, which is a different job.',
      'And it almost never says “no idea”. It fills the gap with something plausible, and plausible is exactly what you have to retract later.',
    ],
    contentDE: [
      'Es ist wirklich gut im Umschreiben, Kürzen, Strukturieren, Übersetzen – und darin, eine leere Seite zu füllen.',
      'Es hat euren Vertrag, euren Kunden, eure Excel-Liste und das Meeting von Dienstag nie gesehen. Außer du fügst es ein.',
      'Es rechnet nicht wirklich. Es schreibt die Zahl, die richtig klingt. Das ist etwas anderes.',
      'Und es sagt fast nie „keine Ahnung“. Es füllt die Lücke mit etwas Plausiblem – und genau das musst du später zurücknehmen.',
    ],
  },
  {
    id: 3,
    type: SlideType.COMPARISON,
    icon: 'Mail',
    title: 'The Mail You Write at 16:40 on a Friday',
    titleDE: 'Die Mail, die man freitags um 16:40 schreibt',
    subtitle: 'The model does not know why the delivery is late. So it invents a reason.',
    subtitleDE: 'Das Modell weiß nicht, warum die Lieferung später kommt. Also erfindet es einen Grund.',
    technique: 'Example 1 · Customer mail',
    techniqueDE: 'Beispiel 1 · Kundenmail',
    codeStandard: 'Write a friendly mail to the customer saying the delivery will be late.',
    codeStandardDE: 'Schreib eine freundliche Mail an den Kunden, dass die Lieferung später kommt.',
    codeOptimized: 'Mail to Ms Berger (purchasing, long-standing customer, prefers short mails).\nFacts: delivery moves from 12 Sept to 26 Sept, cause is a supply shortage on the housing. A partial delivery of 40 units is possible on 12 Sept.\nDo not offer: a discount, express shipping, or any date before 26 Sept.\nForm: max. 120 words, no “we ask for your understanding”, one concrete offer at the end.\nAnything I did not tell you, do not invent — write [CHECK] instead.',
    codeOptimizedDE: 'Mail an Frau Berger (Einkauf, langjährige Kundin, mag kurze Mails).\nFakten: Liefertermin rutscht vom 12.09. auf den 26.09., Grund ist ein Lieferengpass beim Gehäuse. Eine Teillieferung von 40 Stück ist am 12.09. möglich.\nNicht anbieten: Preisnachlass, Expressversand, irgendeinen Termin vor dem 26.09.\nForm: max. 120 Wörter, kein „Wir bitten um Ihr Verständnis“, am Schluss ein konkretes Angebot.\nWas ich dir nicht gesagt habe, erfindest du nicht – schreib [KLÄREN] hin.',
    codeVokuprompt: 'Job:\nOne mail to the customer about the delayed delivery.\n\nMaterial:\nMs Berger, purchasing, long-standing customer, prefers short mails.\n12 Sept → 26 Sept. Cause: supply shortage on the housing. Partial delivery of 40 units possible on 12 Sept.\n\nLimits:\n- No discount, no express shipping, no date before 26 Sept.\n- Do not name the supplier.\n- Anything not in the material above: write [CHECK], do not fill it in.\n\nForm:\n- Max. 120 words, plain German, no filler opening.\n- Last paragraph: the partial delivery as a concrete offer.\n\nDone when:\n- Every fact in the mail appears in the material above, and every gap is marked [CHECK].',
    codeVokupromptDE: 'Auftrag:\nEine Mail an die Kundin wegen der verspäteten Lieferung.\n\nMaterial:\nFrau Berger, Einkauf, langjährige Kundin, mag kurze Mails.\n12.09. → 26.09. Grund: Lieferengpass beim Gehäuse. Teillieferung von 40 Stück am 12.09. möglich.\n\nGrenzen:\n- Kein Preisnachlass, kein Expressversand, kein Termin vor dem 26.09.\n- Den Lieferanten nicht namentlich nennen.\n- Was oben nicht steht: [KLÄREN] schreiben, nicht ergänzen.\n\nForm:\n- Max. 120 Wörter, schlichtes Deutsch, keine Floskel-Einleitung.\n- Letzter Absatz: die Teillieferung als konkretes Angebot.\n\nFertig wenn:\n- Jede Aussage in der Mail steht oben im Material, und jede Lücke ist mit [KLÄREN] markiert.',
    content: 'Same task, two very different results. The short version produces a smooth apology with an invented cause. The second one can only write what actually happened — and it marks the gaps instead of filling them.',
    contentDE: 'Gleiche Aufgabe, zwei sehr verschiedene Ergebnisse. Die kurze Version liefert eine glatte Entschuldigung mit erfundenem Grund. Die zweite kann nur schreiben, was wirklich passiert ist – und markiert die Lücken, statt sie zu füllen.',
  },
  {
    id: 4,
    type: SlideType.CONTENT,
    icon: 'ListChecks',
    title: 'Five Lines That Rescue Almost Any Prompt',
    titleDE: 'Fünf Zeilen, die fast jeden Prompt retten',
    subtitle: 'You rarely need all five. You almost always need two.',
    subtitleDE: 'Du brauchst selten alle fünf. Fast immer brauchst du zwei.',
    content: [
      'Job: what should exist at the end? A mail, a table, one paragraph, a decision.',
      'Material: what did you attach, and what may be used? Text, figures, notes, the old template.',
      'Limits: what must not happen? Nothing promised, nothing invented, nothing deleted, no new numbers.',
      'Form: what should it look like? 150 words, four columns, bullet points, informal tone.',
      'Done when: how do you recognise a good result — and the line that does most of the work: “anything you cannot back up goes at the end as an open question”.',
    ],
    contentDE: [
      'Auftrag: Was soll am Ende dastehen? Eine Mail, eine Tabelle, ein Absatz, eine Entscheidung.',
      'Material: Was hast du beigelegt und was darf benutzt werden? Text, Zahlen, Notizen, die alte Vorlage.',
      'Grenzen: Was darf nicht passieren? Nichts zusagen, nichts erfinden, nichts löschen, keine neuen Zahlen.',
      'Form: Wie soll es aussehen? 150 Wörter, vier Spalten, Stichpunkte, Du-Form.',
      'Fertig wenn: Woran erkennst du ein gutes Ergebnis – und die Zeile, die am meisten bringt: „Was du nicht belegen kannst, kommt ans Ende als offene Frage.“',
    ],
  },
  {
    id: 5,
    type: SlideType.COMPARISON,
    icon: 'ClipboardList',
    title: 'The Minutes Nobody Can Work With',
    titleDE: 'Das Protokoll, mit dem keiner arbeiten kann',
    subtitle: '“Summarise the meeting” gives you a summary. You wanted to know who does what by when.',
    subtitleDE: '„Fasse das Meeting zusammen“ liefert eine Zusammenfassung. Du wolltest wissen, wer bis wann was macht.',
    technique: 'Example 2 · Minutes',
    techniqueDE: 'Beispiel 2 · Protokoll',
    codeStandard: 'Summarise the meeting.',
    codeStandardDE: 'Fasse das Meeting zusammen.',
    codeOptimized: 'Three blocks from the attached transcript:\n1. Decided: the decision — and who said it.\n2. Open: task — name — by when. Only names that appear in the transcript.\n3. Not decided: points that were discussed and postponed.\nNo date in the text: write “no date given”. Do not estimate one.\nNo intro, no closing summary.',
    codeOptimizedDE: 'Aus dem angehängten Transkript drei Blöcke:\n1. Entschieden: der Beschluss – und wer ihn gesagt hat.\n2. Offen: Aufgabe – Name – bis wann. Nur Namen, die im Transkript vorkommen.\n3. Nicht entschieden: Punkte, die diskutiert und vertagt wurden.\nSteht kein Datum im Text: „kein Termin genannt“. Nicht schätzen.\nKeine Einleitung, kein Fazit am Ende.',
    content: 'The trap is not the summary. The trap is the action list a model happily invents: a deadline nobody agreed to, next to a name that was never in the room.',
    contentDE: 'Die Falle ist nicht die Zusammenfassung. Die Falle ist die Aufgabenliste, die ein Modell bereitwillig erfindet: eine Frist, die niemand zugesagt hat, neben einem Namen, der nie im Raum war.',
  },
  {
    id: 6,
    type: SlideType.COMPARISON,
    icon: 'FileSearch',
    title: 'The 43-Page PDF That Arrived at 17:55',
    titleDE: 'Die 43-Seiten-PDF, die um 17:55 kam',
    subtitle: 'Do not ask for a summary. Ask your four questions.',
    subtitleDE: 'Frag nicht nach einer Zusammenfassung. Stell deine vier Fragen.',
    technique: 'Example 3 · Long document',
    techniqueDE: 'Beispiel 3 · Langes Dokument',
    codeStandard: 'Summarise the contract.',
    codeStandardDE: 'Fasse den Vertrag zusammen.',
    codeOptimized: 'Four questions about the attached contract:\n1. Term and automatic renewal?\n2. Notice period and required form?\n3. When may the price rise, and by how much?\n4. Who is liable for an outage, and up to what amount?\nFor each answer: the sentence from the contract plus clause or page.\nIf something is not in there: “not regulated”. Do not add what would be customary.',
    codeOptimizedDE: 'Vier Fragen an den angehängten Vertrag:\n1. Laufzeit und automatische Verlängerung?\n2. Kündigungsfrist und Form?\n3. Wann darf der Preis steigen und um wie viel?\n4. Wer haftet bei Ausfall und bis zu welcher Summe?\nPro Antwort: der Satz aus dem Vertrag plus Paragraf oder Seite.\nSteht etwas nicht drin: „nicht geregelt“. Nicht ergänzen, was üblich wäre.',
    content: 'A summary averages 43 pages down to three paragraphs and quietly drops the one clause that costs money. Four questions with a quote next to each answer are checkable in two minutes.',
    contentDE: 'Eine Zusammenfassung mittelt 43 Seiten auf drei Absätze und lässt genau die Klausel weg, die Geld kostet. Vier Fragen mit Fundstelle sind in zwei Minuten prüfbar.',
  },
  {
    id: 7,
    type: SlideType.COMPARISON,
    icon: 'Calculator',
    title: 'It Writes Numbers. It Does Not Calculate Them.',
    titleDE: 'Es schreibt Zahlen. Es rechnet sie nicht.',
    subtitle: 'Anything that ends up in a budget mail belongs in a table, not in a sentence.',
    subtitleDE: 'Alles, was in einer Budgetmail landet, gehört in eine Tabelle, nicht in einen Satz.',
    technique: 'Example 4 · Doing the maths',
    techniqueDE: 'Beispiel 4 · Rechnen',
    codeStandard: 'We are 14 people, budget 45 € per head. Venue 280 € flat, menu 29 € per person, drinks about 18 € per person, decoration 60 €. Is that enough?',
    codeStandardDE: 'Wir sind 14 Leute, Budget 45 € pro Kopf. Location 280 € pauschal, Menü 29 € pro Person, Getränke ca. 18 € pro Person, Deko 60 €. Reicht das?',
    codeOptimized: 'Do not do this in your head.\nBuild a table: item | unit price | quantity | total.\nItems: venue 280 € flat, menu 29 €/person, drinks 18 €/person, decoration 60 €. 14 people, budget 45 €/person.\nThen: total, budget, difference — and from how many people on the budget breaks.\nShow the calculation, not just the result.',
    codeOptimizedDE: 'Rechne das nicht im Kopf.\nBau eine Tabelle: Position | Einzelpreis | Anzahl | Summe.\nPositionen: Location 280 € pauschal, Menü 29 €/Person, Getränke 18 €/Person, Deko 60 €. 14 Personen, Budget 45 €/Person.\nDanach: Gesamtsumme, Budgetsumme, Differenz – und ab wie vielen Personen das Budget kippt.\nZeig die Rechnung, nicht nur das Ergebnis.',
    content: 'The first version produces a confident number. Sometimes even the right one. You find out which when somebody checks the invoice. A visible table you can scan in ten seconds settles it for good.',
    contentDE: 'Die erste Version liefert eine selbstbewusste Zahl. Manchmal sogar die richtige. Was davon zutrifft, merkst du, wenn jemand die Rechnung prüft. Eine sichtbare Tabelle, die du in zehn Sekunden überfliegst, erledigt das dauerhaft.',
  },
  {
    id: 8,
    type: SlideType.COMPARISON,
    icon: 'MessageSquareX',
    title: 'Tone Is an Instruction, Not a Mood',
    titleDE: 'Ton ist eine Vorgabe, keine Stimmung',
    subtitle: 'With rejections, reminders and bad news, “friendly” is not an instruction.',
    subtitleDE: 'Bei Absagen, Mahnungen und schlechten Nachrichten ist „freundlich“ keine Anweisung.',
    technique: 'Example 5 · Saying no',
    techniqueDE: 'Beispiel 5 · Absage',
    codeStandard: 'Write a polite rejection to the supplier.',
    codeStandardDE: 'Schreib eine höfliche Absage an den Anbieter.',
    codeOptimized: 'Rejection to a supplier whose offer we are not taking. We keep working with them on two other projects, so the relationship has to survive this.\nWe may say: the decision is made, price was not the only reason, we will come back to them for the next tender.\nWe may not say: who won, what the others quoted, or that it was “close”.\nForm: max. 90 words, no filler opening, the decision in the first paragraph as one clear sentence.',
    codeOptimizedDE: 'Absage an einen Anbieter, dessen Angebot wir nicht nehmen. Wir arbeiten mit ihm in zwei anderen Projekten weiter, die Beziehung soll das überleben.\nSagen dürfen wir: Die Entscheidung ist gefallen, der Preis war nicht der einzige Grund, bei der nächsten Ausschreibung kommen wir zurück.\nNicht sagen: wer gewonnen hat, was die anderen geboten haben, oder dass es „knapp“ war.\nForm: max. 90 Wörter, keine Floskel-Einleitung, die Entscheidung im ersten Absatz als ein klarer Satz.',
    content: '“Polite” produces filler. What actually shapes the mail is the list of things you are allowed to say — and the shorter list of things you are not.',
    contentDE: '„Höflich“ erzeugt Floskeln. Was die Mail wirklich formt, ist die Liste dessen, was gesagt werden darf – und die kürzere Liste dessen, was nicht.',
  },
  {
    id: 9,
    type: SlideType.COMPARISON,
    icon: 'Table',
    title: 'If It Has to Go Into Excel, Do Not Ask for Prose',
    titleDE: 'Wenn es nach Excel muss, frag nicht nach Fließtext',
    subtitle: '30 replies, one table, one row each.',
    subtitleDE: '30 Rückmeldungen, eine Tabelle, eine Zeile pro Rückmeldung.',
    technique: 'Example 6 · Structure',
    techniqueDE: 'Beispiel 6 · Struktur',
    codeStandard: 'Read the 30 replies about the room planning and tell me what comes out of it.',
    codeStandardDE: 'Lies die 30 Rückmeldungen zur Raumplanung und sag mir, was rauskommt.',
    codeOptimized: 'Turn the 30 replies into a table, one row per reply.\nColumns: department | request in max. 8 words | preferred date | blocker yes/no.\nIf something is not in the mail: leave the cell empty. Do not guess, do not summarise.\nOutput as a table I can paste into Excel. No text before it, no conclusion after it.',
    codeOptimizedDE: 'Mach aus den 30 Rückmeldungen eine Tabelle, eine Zeile pro Rückmeldung.\nSpalten: Abteilung | Anliegen in max. 8 Wörtern | Wunschtermin | Blocker ja/nein.\nSteht etwas nicht in der Mail: Zelle leer lassen. Nicht raten, nicht zusammenfassen.\nAusgabe als Tabelle, die ich nach Excel kopieren kann. Kein Text davor, kein Fazit danach.',
    content: 'A prose answer is a second reading job. A table is a filter and a sort. And “leave the cell empty” is the line that stops the model from politely inventing a department.',
    contentDE: 'Eine Fließtext-Antwort ist eine zweite Leseaufgabe. Eine Tabelle ist ein Filter und eine Sortierung. Und „Zelle leer lassen“ ist die Zeile, die das Modell davon abhält, höflich eine Abteilung zu erfinden.',
  },
  {
    id: 10,
    type: SlideType.COMPARISON,
    icon: 'SearchCheck',
    title: 'Have It Attack the Draft, Not Compliment It',
    titleDE: 'Lass es den Entwurf angreifen, nicht loben',
    subtitle: '“Is this okay?” always comes back as yes, plus three cosmetic suggestions.',
    subtitleDE: '„Passt das so?“ kommt immer als Ja zurück, plus drei kosmetische Vorschläge.',
    technique: 'Example 7 · Second pair of eyes',
    techniqueDE: 'Beispiel 7 · Gegenlesen',
    codeStandard: 'Check the text again and make it better.',
    codeStandardDE: 'Prüf den Text nochmal und mach ihn besser.',
    codeOptimized: 'Treat the text as a first draft, not as finished.\nFind the three places where the management will ask a follow-up question — and what they will be missing there.\nBack every criticism with the sentence from the text. No style comments.\nIf you find nothing you can back up, write “no objections”. Do not invent criticism to fill the list.',
    codeOptimizedDE: 'Behandle den Text als ersten Entwurf, nicht als fertig.\nFinde die drei Stellen, an denen die Bereichsleitung nachfragt – und was ihnen dort fehlt.\nBeleg jede Kritik mit dem Satz aus dem Text. Keine Stilkritik.\nWenn du nichts Belegbares findest: schreib „keine Einwände“. Erfinde keine Kritik, damit die Liste voll wird.',
    content: 'Two details do the work here: the model has to quote the sentence it criticises, and it is explicitly allowed to find nothing. Leave the second one out and you get three invented objections every single time.',
    contentDE: 'Zwei Details machen hier die Arbeit: Das Modell muss den kritisierten Satz zitieren – und es darf ausdrücklich nichts finden. Lass den zweiten Teil weg und du bekommst jedes Mal drei erfundene Einwände.',
  },
  {
    id: 11,
    type: SlideType.PLAYGROUND,
    icon: 'FlaskConical',
    title: 'Try It: What Is Actually In Your Prompt?',
    titleDE: 'Ausprobieren: Was steht eigentlich in deinem Prompt?',
    subtitle: 'Local check, no model call. It looks for usable instructions, not for length.',
    subtitleDE: 'Lokale Prüfung, kein Modellaufruf. Gesucht werden nutzbare Anweisungen, nicht Länge.',
  },
  {
    id: 12,
    type: SlideType.COMPARISON,
    icon: 'Scissors',
    title: '“Make It Better” Makes It Longer',
    titleDE: '„Mach es besser“ macht es länger',
    subtitle: 'Cutting is the one job where you have to be explicit, or a third paragraph appears.',
    subtitleDE: 'Kürzen ist die eine Aufgabe, bei der du deutlich werden musst – sonst kommt ein dritter Absatz dazu.',
    technique: 'Example 8 · Cutting',
    techniqueDE: 'Beispiel 8 · Kürzen',
    codeStandard: 'Make the text better.',
    codeStandardDE: 'Mach den Text besser.',
    codeOptimized: 'Cut it down to 150 words maximum.\nNo new statements, no new numbers, no new promises.\nCut in this order: filler, repetition, sentences that decide nothing.\nAt the end, list in three bullets what you removed — then I can see whether something important was in there.',
    codeOptimizedDE: 'Kürze auf höchstens 150 Wörter.\nKeine neuen Aussagen, keine neuen Zahlen, keine neuen Zusagen.\nStreich in dieser Reihenfolge: Floskeln, Wiederholungen, Sätze, die nichts entscheiden.\nZeig mir am Ende in drei Stichpunkten, was rausgeflogen ist – dann sehe ich, ob etwas Wichtiges dabei war.',
    content: 'Models are trained to be helpful, and “helpful” statistically means “more”. If you want less, name the number, forbid new content, and ask what was removed.',
    contentDE: 'Modelle sind auf hilfreich trainiert, und „hilfreich“ heißt statistisch „mehr“. Wenn du weniger willst, nenn die Zahl, verbiete neue Inhalte und frag, was gestrichen wurde.',
  },
  {
    id: 13,
    type: SlideType.CONTENT,
    icon: 'ShieldAlert',
    title: 'Four Rules That Spare You the Awkward Conversation',
    titleDE: 'Vier Regeln, die das unangenehme Gespräch ersparen',
    subtitle: 'None of them are about prompting. All of them are about what happens afterwards.',
    subtitleDE: 'Keine davon handelt vom Prompten. Alle handeln davon, was danach passiert.',
    content: [
      'It sends nothing, books nothing, promises nothing and signs nothing. You still do that — and you are the one answering for it.',
      'Salary lists, applications, sick notes, customer data, bank details: only into a tool that is approved for them. When in doubt, ask before you paste.',
      'Check names, figures, deadlines, clauses and quotes. “Sounds plausible” is not evidence; it is the most common source of the mistake.',
      'Same bad result twice? Then material is missing, not wording. Do not write “make it better” — write what exactly was wrong.',
    ],
    contentDE: [
      'Es verschickt nichts, bucht nichts, sagt nichts zu und unterschreibt nichts. Das machst weiterhin du – und du stehst dafür gerade.',
      'Gehaltslisten, Bewerbungen, Krankmeldungen, Kundendaten, Kontodaten: nur in ein Werkzeug, das dafür freigegeben ist. Im Zweifel fragen, bevor du einfügst.',
      'Namen, Zahlen, Fristen, Paragrafen und Zitate gegenprüfen. „Klingt plausibel“ ist kein Beleg, sondern die häufigste Fehlerquelle.',
      'Zweimal dasselbe schlechte Ergebnis? Dann fehlt Material, nicht Formulierung. Schreib nicht „mach es besser“ – schreib, was genau falsch war.',
    ],
  },
  {
    id: 14,
    type: SlideType.END,
    icon: 'CheckCircle2',
    title: 'Takeaways',
    titleDE: 'Zusammenfassung',
    subtitle: 'Good prompts are not magic sentences. They are short, honest work instructions.',
    subtitleDE: 'Gute Prompts sind keine Zaubersätze. Es sind kurze, ehrliche Arbeitsanweisungen.',
    content: [
      'Say what should exist at the end. Hand over the material. Name the red line. Say what it should look like.',
      'One sentence may be enough. Length is not a quality signal, and it does not replace facts you did not provide.',
      'Allow “I don’t know”. Otherwise you get an invention that reads beautifully.',
      'Whatever worked twice belongs in a file of templates — not in your memory and not in the chat history.',
      'Treat it like a very fast new colleague: capable, does not know your company, and never asks.',
    ],
    contentDE: [
      'Sag, was am Ende dastehen soll. Gib das Material mit. Nenn die rote Linie. Sag, wie es aussehen soll.',
      'Ein Satz darf reichen. Länge ist kein Qualitätsmerkmal und ersetzt keine Fakten, die du nicht mitgegeben hast.',
      'Erlaube „weiß ich nicht“. Sonst bekommst du eine Erfindung, die sich gut liest.',
      'Was zweimal funktioniert hat, gehört in eine Datei mit Vorlagen – nicht in dein Gedächtnis und nicht in den Chatverlauf.',
      'Behandle es wie einen sehr schnellen neuen Kollegen: kann viel, kennt euren Laden nicht, fragt nie nach.',
    ],
  },
];

/**
 * Deck B: the office work where a wrong answer is not a clumsy sentence but a
 * wrong figure — offers, budgets, lists, plans, series work, handovers.
 */
export const DECISION_SLIDES: SlideData[] = [
  {
    id: 1,
    type: SlideType.TITLE,
    icon: 'Target',
    title: 'Prompting for Numbers, Plans and Handovers',
    titleDE: 'Prompting für Zahlen, Pläne und Übergaben',
    subtitle: 'Once text turns into a decision, “sounds right” stops being good enough.',
    subtitleDE: 'Wenn aus Text eine Entscheidung wird, reicht „klingt gut“ nicht mehr.',
  },
  {
    id: 2,
    type: SlideType.CONTENT,
    icon: 'TrendingUp',
    title: 'This Is Where a Wrong Answer Gets Expensive',
    titleDE: 'Hier wird eine falsche Antwort teuer',
    subtitle: 'A clumsy sentence you notice while reading. A wrong figure you notice in the follow-up meeting.',
    subtitleDE: 'Einen holprigen Satz merkst du beim Lesen. Eine falsche Zahl merkst du im Nachgespräch.',
    content: [
      'It has no access to your ERP, your calendar, the shared drive or your mailbox. What you do not hand over does not exist for it.',
      'It does not calculate, it formulates. Figures need a visible calculation or a table, not a claim.',
      'It does not distinguish “that is in the export” from “I assumed that” — unless you require it to write the difference down.',
      'And it decides nothing. It prepares. The signature stays with a human who has a name.',
    ],
    contentDE: [
      'Es hat keinen Zugriff auf euer ERP, euren Kalender, das Laufwerk oder euer Postfach. Was du nicht mitgibst, existiert für es nicht.',
      'Es rechnet nicht, es formuliert. Zahlen brauchen eine sichtbare Rechnung oder eine Tabelle, keine Behauptung.',
      'Es unterscheidet nicht zwischen „steht so im Export“ und „habe ich angenommen“ – außer du verlangst, dass es den Unterschied hinschreibt.',
      'Und es entscheidet nichts. Es bereitet vor. Die Unterschrift bleibt bei einem Menschen mit Namen.',
    ],
  },
  {
    id: 3,
    type: SlideType.CONTENT,
    icon: 'BadgeCheck',
    title: 'Three Labels That End Most Arguments',
    titleDE: 'Drei Kennzeichnungen, die die meisten Diskussionen beenden',
    subtitle: 'Backed, assumed, unknown. Ask for the label on every statement.',
    subtitleDE: 'Belegt, angenommen, unbekannt. Verlange die Kennzeichnung an jeder Aussage.',
    content: [
      'BACKED: it says so in the file, the export, the mail — with the place it says it.',
      'ASSUMED: sounds reasonable but is not backed. Has to appear as an assumption, not as a figure.',
      'UNKNOWN: does not appear in the material. A valid answer, and usually the most useful one.',
      'A report without these three categories reads better and is more dangerous. Reading better is precisely what makes it dangerous.',
      'This is the sixth line next to job, material, limits, form and done-when: evidence — how do I know it is true?',
    ],
    contentDE: [
      'BELEGT: Steht so in der Datei, im Export, in der Mail – mit Fundstelle.',
      'ANGENOMMEN: Klingt vernünftig, ist aber nicht belegt. Muss als Annahme dastehen, nicht als Zahl.',
      'UNBEKANNT: Kommt in den Unterlagen nicht vor. Eine gültige Antwort, meistens die nützlichste.',
      'Ein Bericht ohne diese drei Kategorien liest sich besser und ist gefährlicher. Das Gefährliche ist genau, dass er sich besser liest.',
      'Das ist die sechste Zeile neben Auftrag, Material, Grenzen, Form und Fertig-wenn: Nachweis – woran erkenne ich, dass es stimmt?',
    ],
  },
  {
    id: 4,
    type: SlideType.COMPARISON,
    icon: 'Scale',
    title: 'Three Offers, One Signature',
    titleDE: 'Drei Angebote, eine Unterschrift',
    subtitle: '“Which one is best?” answers a question you never asked.',
    subtitleDE: '„Welches ist das beste?“ beantwortet eine Frage, die du nie gestellt hast.',
    technique: 'Example 1 · Comparing offers',
    techniqueDE: 'Beispiel 1 · Angebotsvergleich',
    codeStandard: 'Which of the three offers is the best one?',
    codeStandardDE: 'Welches der drei Angebote ist das beste?',
    codeOptimized: 'Compare the three attached offers as a table.\nCriteria in this order: total cost over 3 years, delivery date, support hours, notice period.\nIn each cell: the figure plus where it says so (offer, page). If the offer does not say: “not stated” — do not estimate and do not make it comparable by inventing.\nThen: a recommendation in two sentences and the one question that has to be settled before we sign.',
    codeOptimizedDE: 'Vergleich der drei angehängten Angebote als Tabelle.\nKriterien in dieser Reihenfolge: Gesamtkosten über 3 Jahre, Liefertermin, Support-Zeiten, Kündigungsfrist.\nPro Zelle: die Zahl plus Fundstelle (Angebot, Seite). Fehlt die Angabe: „nicht angegeben“ – nicht schätzen und nicht durch Erfinden vergleichbar machen.\nDanach: eine Empfehlung in zwei Sätzen und die eine Frage, die vor der Unterschrift geklärt sein muss.',
    content: '“Best” depends on criteria the model does not have, so it picks the offer that is written most confidently. Give it your criteria and you get a comparison instead of an opinion.',
    contentDE: '„Am besten“ hängt an Kriterien, die das Modell nicht hat – also nimmt es das Angebot, das am selbstbewusstesten formuliert ist. Mit deinen Kriterien wird daraus ein Vergleich statt einer Meinung.',
  },
  {
    id: 5,
    type: SlideType.COMPARISON,
    icon: 'Table2',
    title: 'The List Three People Maintained',
    titleDE: 'Die Liste, die drei Leute gepflegt haben',
    subtitle: 'Cleaning data is where “helpful” quietly deletes rows.',
    subtitleDE: 'Beim Bereinigen löscht „hilfsbereit“ ganz leise Zeilen.',
    technique: 'Example 2 · Cleaning data',
    techniqueDE: 'Beispiel 2 · Datenpflege',
    codeStandard: 'Clean up the customer list.',
    codeStandardDE: 'Bereinige die Kundenliste.',
    codeOptimized: 'Clean the attached list by exactly these rules:\n1. Duplicates by customer number — not by name.\n2. All dates as YYYY-MM-DD.\n3. Empty fields stay empty. Add nothing, derive nothing.\n4. Delete nothing. Suspicious rows get a “check” column with the reason.\nAt the end: how many rows changed, how many flagged, how many untouched.',
    codeOptimizedDE: 'Bereinige die angehängte Liste nach genau diesen Regeln:\n1. Dubletten nach Kundennummer – nicht nach Name.\n2. Alle Daten als JJJJ-MM-TT.\n3. Leere Felder bleiben leer. Nichts ergänzen, nichts ableiten.\n4. Nichts löschen. Verdächtige Zeilen bekommen die Spalte „Prüfen“ mit dem Grund.\nAm Ende: wie viele Zeilen geändert, wie viele markiert, wie viele unverändert.',
    content: 'The counting line at the end is not bureaucracy. It is the only way you notice that 140 rows went in and 118 came out.',
    contentDE: 'Die Zählzeile am Ende ist keine Bürokratie. Sie ist die einzige Chance zu merken, dass 140 Zeilen rein- und 118 rausgegangen sind.',
  },
  {
    id: 6,
    type: SlideType.COMPARISON,
    icon: 'Calculator',
    title: 'The Figure You Take Into the Budget Meeting',
    titleDE: 'Die Zahl, mit der du ins Budgetgespräch gehst',
    subtitle: 'Assumptions belong in the answer, not in your head.',
    subtitleDE: 'Annahmen gehören in die Antwort, nicht in deinen Kopf.',
    technique: 'Example 3 · Projection',
    techniqueDE: 'Beispiel 3 · Hochrechnung',
    codeStandard: 'Will our budget last until the end of the year?',
    codeStandardDE: 'Reicht unser Budget bis Jahresende?',
    codeOptimized: 'Projection from the attached cost export for January to August.\nCalculate it so I can follow it: monthly average, projection to December, difference to budget.\nList your assumptions one by one (for example: no more one-off items, same headcount).\nThree scenarios: as before, +10 %, −10 %.\nAnd: which figure are you missing to turn this into a decision paper?',
    codeOptimizedDE: 'Hochrechnung aus dem angehängten Kostenexport Januar bis August.\nRechne nachvollziehbar: Monatsschnitt, Hochrechnung bis Dezember, Differenz zum Budget.\nNenn deine Annahmen einzeln (zum Beispiel: keine Sonderposten mehr, gleicher Personalstand).\nDrei Szenarien: wie gehabt, +10 %, −10 %.\nUnd: welche Zahl fehlt dir, um daraus eine Entscheidungsvorlage zu machen?',
    content: 'The last line is the useful one. It turns “here is a figure” into “here is what is still missing” — and that is the sentence that saves you in the meeting.',
    contentDE: 'Die letzte Zeile ist die nützliche. Sie macht aus „hier ist eine Zahl“ ein „das fehlt noch“ – und genau dieser Satz rettet dich im Termin.',
  },
  {
    id: 7,
    type: SlideType.COMPARISON,
    icon: 'Map',
    title: 'The Plan Somebody Put Together “Real Quick”',
    titleDE: 'Der Plan, den jemand „mal eben“ gemacht hat',
    subtitle: 'Treat it as the floor, not as the result — and allow it to come back clean.',
    subtitleDE: 'Behandle ihn als Untergrenze, nicht als Ergebnis – und lass ein „trägt“ zu.',
    technique: 'Example 4 · Checking a plan',
    techniqueDE: 'Beispiel 4 · Planprüfung',
    codeStandard: 'Does the project plan work like this?',
    codeStandardDE: 'Passt der Projektplan so?',
    codeOptimized: 'Treat the attached plan as a draft and as the minimum standard, not as the result.\nKeep everything that is backed: dates, owners, work already done.\nAdd only where something is missing: dependencies between the steps, who decides in case of doubt, what happens if step 2 slips by two weeks.\nNo longer text without new content. If nothing substantial is missing, write “the plan holds” and justify that in three sentences.',
    codeOptimizedDE: 'Behandle den angehängten Plan als Entwurf und als Mindeststandard, nicht als Ergebnis.\nBehalte alles, was belegt ist: Termine, Zuständige, bereits Erledigtes.\nErgänze nur, wo etwas fehlt: Abhängigkeiten zwischen den Schritten, wer im Zweifel entscheidet, was passiert, wenn Schritt 2 zwei Wochen rutscht.\nKein längerer Text ohne neuen Inhalt. Wenn nichts Wesentliches fehlt: schreib „Plan trägt“ und begründe das in drei Sätzen.',
    content: 'Calling it a draft is a challenge, not an insult. Without explicit permission to say “this holds”, you get a longer plan, which is not the same as a better one.',
    contentDE: '„Entwurf“ ist eine Herausforderung, keine Beleidigung. Ohne die ausdrückliche Erlaubnis, „trägt“ zu sagen, bekommst du einen längeren Plan – und das ist kein besserer.',
  },
  {
    id: 8,
    type: SlideType.COMPARISON,
    icon: 'Layers',
    title: '60 Responses and One Afternoon',
    titleDE: '60 Rückläufer und ein Nachmittag',
    subtitle: 'Long jobs fail in the middle. Slice them and count after every slice.',
    subtitleDE: 'Lange Aufgaben scheitern in der Mitte. Zerleg sie und zähl nach jeder Scheibe.',
    technique: 'Example 5 · Series work',
    techniqueDE: 'Beispiel 5 · Serienarbeit',
    codeStandard: 'Evaluate the 60 responses.',
    codeStandardDE: 'Werte die 60 Rückläufer aus.',
    codeOptimized: 'Work through the 60 responses in blocks of 10.\nSame structure per entry: name | agrees yes/no/unclear | note in max. 10 words.\nAfter each block: interim status with the counts (how many yes, no, unclear) — then stop and wait for “continue”.\nEntries that do not fit the scheme go on a “to clarify” pile. Do not make them fit.',
    codeOptimizedDE: 'Arbeite die 60 Rückläufer in Blöcken zu 10 ab.\nPro Eintrag dieselbe Struktur: Name | Zustimmung ja/nein/unklar | Anmerkung in max. 10 Wörtern.\nNach jedem Block: Zwischenstand mit Zählung (wie viele ja, nein, unklar) – dann stopp und warte auf „weiter“.\nEinträge, die nicht ins Schema passen, kommen auf einen Stapel „Klärfall“. Nicht passend machen.',
    content: 'Somewhere around item 35 the format drifts, and item 51 gets quietly reshaped to fit. Blocks with a count after each one make that visible while it is still cheap to fix.',
    contentDE: 'Ungefähr ab Eintrag 35 driftet das Format, und Eintrag 51 wird still passend gemacht. Blöcke mit Zählung machen das sichtbar, solange es noch billig zu reparieren ist.',
  },
  {
    id: 9,
    type: SlideType.COMPARISON,
    icon: 'Handshake',
    title: 'The Handover Before Your Holiday',
    titleDE: 'Die Übergabe vor dem Urlaub',
    subtitle: 'Your stand-in was in none of the meetings and cannot read this chat.',
    subtitleDE: 'Deine Vertretung war in keinem der Termine und kann diesen Chat nicht lesen.',
    technique: 'Example 6 · Handover',
    techniqueDE: 'Beispiel 6 · Übergabe',
    codeStandard: 'Write a handover for my stand-in.',
    codeStandardDE: 'Schreib eine Übergabe für meine Vertretung.',
    codeOptimized: 'Handover for a colleague who was in none of the meetings and cannot see this chat.\nFrom my notes, per item: status today | next step | by when | who decides | where the file is | what must not be promised under any circumstances.\nAnything you cannot back up from my notes goes at the end as a question to me — not as an assumption in the middle of the text.\nOrder: whatever is due in the first three days comes first.',
    codeOptimizedDE: 'Übergabe für eine Kollegin, die in keinem der Termine war und diesen Chat nicht sehen kann.\nAus meinen Notizen, pro Vorgang: Stand heute | nächster Schritt | bis wann | wer entscheidet | wo die Datei liegt | was auf keinen Fall zugesagt werden darf.\nWas du aus meinen Notizen nicht belegen kannst, kommt ans Ende als Frage an mich – nicht als Annahme mitten im Text.\nReihenfolge: was in den ersten drei Tagen ansteht, zuerst.',
    content: 'Everything you know and never wrote down is invisible here. Saying that out loud turns the gaps into a short list of questions instead of confident fiction.',
    contentDE: 'Alles, was du weißt und nie aufgeschrieben hast, ist hier unsichtbar. Wenn du das ausdrücklich sagst, werden aus den Lücken ein paar Rückfragen statt selbstbewusster Erfindung.',
  },
  {
    id: 10,
    type: SlideType.COMPARISON,
    icon: 'FileText',
    title: 'A Status Report People Can Believe',
    titleDE: 'Ein Statusbericht, dem man glauben kann',
    subtitle: 'Every figure gets a source. Everything else goes under “unresolved”.',
    subtitleDE: 'Jede Zahl bekommt eine Quelle. Alles andere kommt unter „ungeklärt“.',
    technique: 'Example 7 · Status report',
    techniqueDE: 'Beispiel 7 · Statusbericht',
    codeStandard: 'Write the status report for Wednesday.',
    codeStandardDE: 'Schreib den Statusbericht für Mittwoch.',
    codeOptimized: 'Status report from the attached notes and the cost export.\nPer item: status | source (file and date) | still open | risk in one sentence.\nNo item without a source. Anything you cannot back up goes under “unresolved” — not under “on track”.\nOne page maximum. Traffic-light colours only if you also write down the rule you used to assign them.',
    codeOptimizedDE: 'Statusbericht aus den angehängten Notizen und dem Kostenexport.\nPro Punkt: Stand | Quelle (Datei und Datum) | noch offen | Risiko in einem Satz.\nKein Punkt ohne Quelle. Was du nicht belegen kannst, kommt unter „ungeklärt“ – nicht unter „läuft“.\nMaximal eine Seite. Ampelfarben nur, wenn du die Regel dazuschreibst, nach der du sie vergeben hast.',
    content: 'Green without a rule is a mood. The moment the model has to write down why something is green, half of it turns amber — and that is the actual status.',
    contentDE: 'Grün ohne Regel ist eine Stimmung. Sobald das Modell begründen muss, warum etwas grün ist, wird die Hälfte gelb – und das ist der tatsächliche Stand.',
  },
  {
    id: 11,
    type: SlideType.PLAYGROUND,
    icon: 'FlaskConical',
    title: 'Try It: Would You Sign Off on This Prompt?',
    titleDE: 'Ausprobieren: Würdest du diesen Prompt abzeichnen?',
    subtitle: 'Local check, no model call. It looks for sources, limits and a stopping point.',
    subtitleDE: 'Lokale Prüfung, kein Modellaufruf. Gesucht werden Quellen, Grenzen und ein Endpunkt.',
  },
  {
    id: 12,
    type: SlideType.COMPARISON,
    icon: 'ScanSearch',
    title: 'Ask What Is Missing, Not What Is Wrong',
    titleDE: 'Frag, was fehlt – nicht, was falsch ist',
    subtitle: 'A concept can be flawless and still unusable because nobody is responsible.',
    subtitleDE: 'Ein Konzept kann fehlerfrei und trotzdem unbrauchbar sein, weil niemand zuständig ist.',
    technique: 'Example 8 · Gap check',
    techniqueDE: 'Beispiel 8 · Lückenprüfung',
    codeStandard: 'Review the concept.',
    codeStandardDE: 'Prüf das Konzept.',
    codeOptimized: 'Check the attached concept for gaps only, not for style.\nLook for: missing ownership, missing deadline, missing escalation, missing sign-off, missing costs.\nPer gap: where in the document | what is missing | what goes wrong if it stays missing.\nNo invented requirements. If a point is covered, leave it out instead of praising it.',
    codeOptimizedDE: 'Prüf das angehängte Konzept nur auf Lücken, nicht auf Stil.\nSuch nach: fehlender Zuständigkeit, fehlender Frist, fehlender Eskalation, fehlender Abnahme, fehlenden Kosten.\nPro Lücke: Stelle im Dokument | was fehlt | was schiefgeht, wenn es fehlt.\nKeine erfundenen Anforderungen. Wenn ein Punkt geregelt ist, lass ihn weg, statt ihn zu loben.',
    content: 'A review finds sentences. A gap check finds the missing owner — and that is the thing that stops the project in week six.',
    contentDE: 'Ein Review findet Sätze. Eine Lückenprüfung findet die fehlende Zuständigkeit – und die stoppt das Projekt in Woche sechs.',
  },
  {
    id: 13,
    type: SlideType.CONTENT,
    icon: 'OctagonAlert',
    title: 'When to Stop Prompting',
    titleDE: 'Wann du aufhören solltest zu prompten',
    subtitle: 'Some answers are not a wording problem.',
    subtitleDE: 'Manche Antworten sind kein Formulierungsproblem.',
    content: [
      'Same wrong result twice: material is missing, not wording. Attach the file, or say concretely what was wrong.',
      'The answer depends on a decision that is not yours: then go and get the decision. A model cannot make it for you, and will act as if it can.',
      'You cannot check the result: then it is not a result, it is a risk with formatting.',
      'Doing it by hand is faster: then do it by hand. Three prompts for one line of text is not tool use, that is a hobby.',
    ],
    contentDE: [
      'Zweimal dasselbe falsche Ergebnis: Es fehlt Material, nicht Formulierung. Leg die Datei bei oder sag konkret, was falsch war.',
      'Die Antwort hängt an einer Entscheidung, die dir nicht gehört: Dann hol die Entscheidung. Ein Modell kann sie nicht treffen und tut trotzdem so.',
      'Du kannst das Ergebnis nicht prüfen: Dann ist es kein Ergebnis, sondern ein Risiko mit Formatierung.',
      'Von Hand geht es schneller: Dann mach es von Hand. Drei Prompts für eine Zeile Text sind kein Werkzeuggebrauch, das ist ein Hobby.',
    ],
  },
  {
    id: 14,
    type: SlideType.END,
    icon: 'CheckCircle2',
    title: 'Takeaways',
    titleDE: 'Zusammenfassung',
    subtitle: 'The model prepares the decision. It does not take it, and it does not sign it.',
    subtitleDE: 'Das Modell bereitet die Entscheidung vor. Es trifft sie nicht und unterschreibt sie nicht.',
    content: [
      'Figures need a visible calculation. Statements need a source. Plans need someone who decides.',
      '“Unknown” is a good answer. “Roughly” is not.',
      'Long jobs go into blocks, with a count after each block. Otherwise you notice the break at the very end.',
      'Write for readers without prior knowledge: the stand-in, the management, yourself in six weeks.',
      'Whatever worked twice becomes a template. The chat history is not a filing system.',
    ],
    contentDE: [
      'Zahlen brauchen eine sichtbare Rechnung. Aussagen brauchen eine Quelle. Pläne brauchen jemanden, der entscheidet.',
      '„Unbekannt“ ist eine gute Antwort. „Ungefähr“ ist keine.',
      'Lange Aufgaben in Blöcke, mit Zählung nach jedem Block. Sonst merkst du den Bruch erst ganz am Ende.',
      'Schreib für Leser ohne Vorwissen: die Vertretung, die Bereichsleitung, dich selbst in sechs Wochen.',
      'Was zweimal funktioniert hat, wird eine Vorlage. Der Chatverlauf ist kein Ablagesystem.',
    ],
  },
];

export const GUIDE_SLIDES: Record<GuideMode, SlideData[]> = {
  desk: DESK_SLIDES,
  decisions: DECISION_SLIDES,
};
