import { GuideMode, SlideData, SlideType } from './types';

export const CODING_SLIDES: SlideData[] = [
  {
    id: 1,
    type: SlideType.TITLE,
    icon: 'BrainCircuit',
    title: 'Operational Prompting for Real Software Work',
    titleDE: 'Operatives Prompting für echte Software-Arbeit',
    subtitle: 'How to control LLMs and coding agents with context, constraints, validation, tools, and explicit stopping conditions.',
    subtitleDE: 'Wie man LLMs und Coding-Agenten mit Kontext, Einschränkungen, Validierung, Werkzeugen und expliziten Abbruchbedingungen steuert.',
  },
  {
    id: 2,
    type: SlideType.CONTENT,
    icon: 'AlertTriangle',
    title: 'Useful, Fast, and Still Unreliable Without Control',
    titleDE: 'Nützlich, schnell und ohne Kontrolle trotzdem unzuverlässig',
    subtitle: 'LLMs can accelerate delivery, but only if you treat prompting as operational control.',
    subtitleDE: 'LLMs können die Lieferung beschleunigen – aber nur, wenn Prompting als operative Steuerung behandelt wird.',
    content: [
      'Models are good at drafting, summarising, transforming, and navigating large codebases.',
      'They are still weak at silent assumptions, stale facts, arithmetic, and stopping at the right boundary.',
      'A better prompt does not create expertise; it allocates attention, constrains behavior, and demands proof.',
      'Your job is not to sound smart. Your job is to make the work more structured, more verifiable, easier to validate, and less likely to drift.',
    ],
    contentDE: [
      'Modelle sind gut beim Entwerfen, Zusammenfassen, Transformieren und Navigieren durch große Codebasen.',
      'Sie bleiben schwach bei stillen Annahmen, veralteten Fakten, Arithmetik und beim Stoppen an der richtigen Grenze.',
      'Ein besserer Prompt erzeugt keine Expertise; er lenkt Aufmerksamkeit, begrenzt Verhalten und fordert Beweise ein.',
      'Deine Aufgabe ist nicht, intelligent zu klingen. Deine Aufgabe ist, die Arbeit strukturierter, prüfbarer, leichter zu validieren und weniger driftanfällig zu machen.',
    ],
  },
  {
    id: 3,
    type: SlideType.COMPARISON,
    icon: 'Bug',
    title: 'Weak Prompts Are Vague Tickets',
    titleDE: 'Schwache Prompts sind vage Tickets',
    subtitle: 'Bug-fix requests fail when they do not define evidence, boundaries, and stopping conditions.',
    subtitleDE: 'Bugfix-Anfragen scheitern, wenn sie keine Belege, Grenzen und Abbruchbedingungen definieren.',
    technique: 'Example 1 · Bug fix',
    techniqueDE: 'Beispiel 1 · Bugfix',
    codeStandard: 'Fix the login bug and add tests.',
    codeStandardDE: 'Behebe den Login-Bug und füge Tests hinzu.',
    codeOptimized: 'Goal: Fix the login bug in AuthController.\nContext: Inspect src/AuthController.ts, compare the failing request path with tests/auth/login.spec.ts, and preserve the public API.\nConstraints: Change only the affected login path, add one regression test, and do not weaken existing checks.\nValidation: Run npm test and npm run typecheck, then paste the raw output.\nDone when: The new regression test fails before the fix, passes after the fix, and the public API is unchanged.',
    codeOptimizedDE: 'Ziel: Den Login-Bug in AuthController beheben.\nKontext: src/AuthController.ts prüfen, den fehlschlagenden Request-Pfad mit tests/auth/login.spec.ts vergleichen und die öffentliche API beibehalten.\nEinschränkungen: Nur den betroffenen Login-Pfad ändern, einen Regressionstest ergänzen und bestehende Checks nicht abschwächen.\nValidierung: npm test und npm run typecheck ausführen und die rohe Ausgabe einfügen.\nFertig wenn: Der neue Regressionstest vor dem Fix fehlschlägt, nach dem Fix besteht und die öffentliche API unverändert bleibt.',
    codeVokuprompt: 'Goal:\nFix the login regression in AuthController.\n\nContext:\nInspect src/AuthController.ts, compare the failing path with tests/auth/login.spec.ts, and keep the public API unchanged.\n\nConstraints:\n- Do not modify unrelated routes or helper utilities.\n- Add exactly one regression test for the broken path.\n\nValidation:\n- Run npm test and npm run typecheck.\n- Paste raw output.\n\nDone when:\n- The regression test fails before the fix, passes after the fix, and no public API changes are introduced.\n\nState update:\n- Record the root cause and the regression pattern in implementation-notes.md.',
    codeVokupromptDE: 'Ziel:\nDie Login-Regression in AuthController beheben.\n\nKontext:\nsrc/AuthController.ts prüfen, den fehlschlagenden Pfad mit tests/auth/login.spec.ts vergleichen und die öffentliche API unverändert lassen.\n\nEinschränkungen:\n- Keine nicht betroffenen Routen oder Hilfsfunktionen ändern.\n- Genau einen Regressionstest für den defekten Pfad ergänzen.\n\nValidierung:\n- npm test und npm run typecheck ausführen.\n- Rohe Ausgabe einfügen.\n\nFertig wenn:\n- Der Regressionstest vor dem Fix fehlschlägt, nach dem Fix besteht und keine Änderungen an der öffentlichen API entstehen.\n\nStatus-Update:\n- Grundursache und Regressionsmuster in implementation-notes.md festhalten.',
    content: 'The weak version sounds like a Jira title. The stronger version says what to inspect, what must not change, which checks prove correctness, and when the agent is allowed to stop.',
    contentDE: 'Die schwache Version klingt wie ein Jira-Titel. Die stärkere Version sagt, was untersucht werden soll, was sich nicht ändern darf, welche Checks Korrektheit beweisen und wann der Agent stoppen darf.',
  },
  {
    id: 4,
    type: SlideType.CONTENT,
    icon: 'ListChecks',
    title: 'The Contract Shape: Goal, Context, Constraints, Done-When',
    titleDE: 'Die Vertragsform: Ziel, Kontext, Einschränkungen, Fertig-wenn',
    subtitle: 'These four fields turn a vague request into executable scope.',
    subtitleDE: 'Diese vier Felder verwandeln eine vage Anfrage in ausführbaren Scope.',
    content: [
      'Goal: What should change? Keep it concrete and minimal.',
      'Context: Which files, logs, specs, screenshots, or examples matter?',
      'Constraints: What must not change? Public APIs, unrelated files, rollout limits, compliance boundaries.',
      'Done-When: What exact condition allows the agent to stop? Passing checks, raw output, observed behavior, screenshot match.',
      'Add validation whenever possible: tests, builds, diffs, citations, or tool output as witnesses.',
    ],
    contentDE: [
      'Ziel: Was soll sich ändern? Konkret und minimal formulieren.',
      'Kontext: Welche Dateien, Logs, Spezifikationen, Screenshots oder Beispiele sind relevant?',
      'Einschränkungen: Was darf sich nicht ändern? Öffentliche APIs, nicht betroffene Dateien, Rollout-Grenzen, Compliance-Bedingungen.',
      'Fertig-wenn: Welche exakte Bedingung erlaubt dem Agenten zu stoppen? Bestandene Checks, rohe Ausgabe, beobachtetes Verhalten, passende Screenshots.',
      'Wenn möglich Validierung hinzufügen: Tests, Builds, Diffs, Zitate oder Tool-Ausgabe als Zeugen.',
    ],
  },
  {
    id: 5,
    type: SlideType.COMPARISON,
    icon: 'Rows3',
    title: 'Coding Agents Need Scope Boundaries',
    titleDE: 'Coding-Agenten brauchen Scope-Grenzen',
    subtitle: 'Migration work goes off the rails when the agent is allowed to rewrite the whole system.',
    subtitleDE: 'Migrationsarbeit entgleist, wenn der Agent das ganze System umschreiben darf.',
    technique: 'Example 2 · Legacy migration',
    techniqueDE: 'Beispiel 2 · Legacy-Migration',
    codeStandard: 'Migrate this legacy dashboard to React.',
    codeStandardDE: 'Migriere dieses Legacy-Dashboard nach React.',
    codeOptimized: 'Goal: Migrate one vertical slice of the dashboard from jQuery to React.\nContext: Compare legacy/reports.html with src/features/reports and capture before/after screenshots.\nConstraints: Keep current behavior stable, migrate only the invoice filter flow, and document every decision.\nValidation: Run the existing UI checks, compare screenshots, and list any remaining gaps.\nDone when: One slice is migrated, old behavior is still stable, and the decisions are written down.',
    codeOptimizedDE: 'Ziel: Einen vertikalen Slice des Dashboards von jQuery nach React migrieren.\nKontext: legacy/reports.html mit src/features/reports vergleichen und Vorher/Nachher-Screenshots erfassen.\nEinschränkungen: Aktuelles Verhalten stabil halten, nur den Invoice-Filter-Flow migrieren und jede Entscheidung dokumentieren.\nValidierung: Vorhandene UI-Checks ausführen, Screenshots vergleichen und verbleibende Lücken auflisten.\nFertig wenn: Ein Slice migriert ist, das alte Verhalten stabil bleibt und die Entscheidungen dokumentiert sind.',
    codeVokuprompt: 'Goal:\nMigrate one vertical slice of the legacy dashboard to React.\n\nContext:\nCompare legacy/reports.html with src/features/reports and capture before/after screenshots.\n\nConstraints:\n- Keep old behavior stable.\n- Migrate only the invoice filter flow.\n- Document decisions and known gaps.\n\nValidation:\n- Run the existing UI checks.\n- Compare screenshots or observable behavior.\n\nDone when:\n- One slice is migrated, screenshots match, and open decisions are documented.\n\nState update:\n- Write the migration decisions and any unchanged behavior into implementation-notes.md or repo docs.',
    codeVokupromptDE: 'Ziel:\nEinen vertikalen Slice des Legacy-Dashboards nach React migrieren.\n\nKontext:\nlegacy/reports.html mit src/features/reports vergleichen und Vorher/Nachher-Screenshots erfassen.\n\nEinschränkungen:\n- Altes Verhalten stabil halten.\n- Nur den Invoice-Filter-Flow migrieren.\n- Entscheidungen und bekannte Lücken dokumentieren.\n\nValidierung:\n- Die vorhandenen UI-Checks ausführen.\n- Screenshots oder beobachtbares Verhalten vergleichen.\n\nFertig wenn:\n- Ein Slice migriert ist, die Screenshots passen und offene Entscheidungen dokumentiert sind.\n\nStatus-Update:\n- Migrationsentscheidungen und bewusst unverändertes Verhalten in implementation-notes.md oder Repo-Dokumentation schreiben.',
    content: '“Migrate the dashboard” is an invitation to sprawl. “Migrate one vertical slice, prove behavior parity, and document decisions” creates a boundary the agent can actually respect.',
    contentDE: '„Migriere das Dashboard“ ist eine Einladung zum Ausufern. „Migriere einen vertikalen Slice, belege Verhaltensparität und dokumentiere Entscheidungen“ schafft eine Grenze, die der Agent tatsächlich respektieren kann.',
  },
  {
    id: 6,
    type: SlideType.COMPARISON,
    icon: 'DatabaseZap',
    title: 'Facts Require Retrieval',
    titleDE: 'Fakten brauchen Retrieval',
    subtitle: 'SQL debugging starts with schema and evidence, not with confident guessing.',
    subtitleDE: 'SQL-Debugging beginnt mit Schema und Belegen – nicht mit selbstsicherem Raten.',
    technique: 'Example 3 · SQL debugging',
    techniqueDE: 'Beispiel 3 · SQL-Debugging',
    codeStandard: 'This SQL query is failing. Fix it.',
    codeStandardDE: 'Diese SQL-Query schlägt fehl. Behebe sie.',
    codeOptimized: 'Goal: Identify the root cause of the failing SQL query.\nContext: Inspect the schema first, then compare the working query with the failing query from the log.\nConstraints: Produce the minimal fix, do not add indexes without evidence, and do not rewrite unrelated joins.\nValidation: Show the schema evidence, name the exact mismatch, and provide the corrected query.\nDone when: The root cause is explicit and the minimal fix is ready to run.',
    codeOptimizedDE: 'Ziel: Die Grundursache der fehlschlagenden SQL-Query identifizieren.\nKontext: Zuerst das Schema prüfen, dann die funktionierende Query mit der fehlschlagenden Query aus dem Log vergleichen.\nEinschränkungen: Den minimalen Fix liefern, keine Indizes ohne Beleg hinzufügen und keine nicht betroffenen Joins umschreiben.\nValidierung: Schema-Belege zeigen, den exakten Mismatch benennen und die korrigierte Query liefern.\nFertig wenn: Die Grundursache explizit benannt ist und der minimale Fix ausführbar bereitsteht.',
    codeVokuprompt: 'Goal:\nFind the root cause of the failing SQL query.\n\nContext:\nInspect the schema first, then compare the working query with the failing query from the production log.\n\nConstraints:\n- Produce the minimal fix.\n- Do not add indexes or rewrite unrelated joins without evidence.\n\nValidation:\n- Show schema evidence.\n- Identify the exact mismatch.\n- Provide the corrected query.\n\nDone when:\n- The root cause is explicit and the minimal corrected query is ready.\n\nState update:\n- Record the mismatch pattern and the verified schema facts in implementation-notes.md.',
    codeVokupromptDE: 'Ziel:\nDie Grundursache der fehlschlagenden SQL-Query finden.\n\nKontext:\nZuerst das Schema prüfen, dann die funktionierende Query mit der fehlschlagenden Query aus dem Produktionslog vergleichen.\n\nEinschränkungen:\n- Den minimalen Fix liefern.\n- Keine Indizes hinzufügen oder nicht betroffene Joins umschreiben ohne Beleg.\n\nValidierung:\n- Schema-Belege zeigen.\n- Den exakten Mismatch identifizieren.\n- Die korrigierte Query liefern.\n\nFertig wenn:\n- Die Grundursache explizit benannt ist und die minimal korrigierte Query bereitsteht.\n\nStatus-Update:\n- Mismatch-Muster und verifizierte Schema-Fakten in implementation-notes.md festhalten.',
    content: 'Facts do not come from vibes. They come from retrieval: schema inspection, logs, specs, current docs, and side-by-side comparisons of working versus failing behavior.',
    contentDE: 'Fakten kommen nicht aus Bauchgefühl. Sie kommen aus Retrieval: Schema-Inspektion, Logs, Spezifikationen, aktuellen Dokumenten und Gegenüberstellungen von funktionierendem versus fehlschlagendem Verhalten.',
  },
  {
    id: 7,
    type: SlideType.COMPARISON,
    icon: 'Calculator',
    title: 'Arithmetic and Repeatable Logic Require Tools or Code',
    titleDE: 'Arithmetik und wiederholbare Logik brauchen Werkzeuge oder Code',
    subtitle: 'If the result matters, ask for executable logic and show the output.',
    subtitleDE: 'Wenn das Ergebnis wichtig ist, fordere ausführbare Logik an und zeige die Ausgabe.',
    technique: 'Tool use for repeatable logic',
    techniqueDE: 'Werkzeuge für wiederholbare Logik',
    codeStandard: 'How many CI runners do we need if six jobs average 8, 11, 7, 5, 14, and 9 minutes and we want the pipeline below 12 minutes?',
    codeStandardDE: 'Wie viele CI-Runner brauchen wir, wenn sechs Jobs im Schnitt 8, 11, 7, 5, 14 und 9 Minuten dauern und die Pipeline unter 12 Minuten bleiben soll?',
    codeOptimized: 'Goal: Calculate the minimum number of CI runners needed.\nContext: Use the six job durations 8, 11, 7, 5, 14, and 9 minutes and target a wall-clock time below 12 minutes.\nConstraints: Do not estimate mentally. Use executable code or a spreadsheet-style calculation and show the raw result.\nValidation: Print the calculation and the final runner count.\nDone when: The answer comes from repeatable tool output, not intuition.',
    codeOptimizedDE: 'Ziel: Die minimale Anzahl benötigter CI-Runner berechnen.\nKontext: Die sechs Job-Dauern 8, 11, 7, 5, 14 und 9 Minuten verwenden und eine Gesamtzeit unter 12 Minuten anstreben.\nEinschränkungen: Nicht mental schätzen. Ausführbaren Code oder eine tabellarische Berechnung verwenden und das rohe Ergebnis zeigen.\nValidierung: Die Berechnung und die finale Runner-Zahl ausgeben.\nFertig wenn: Die Antwort aus wiederholbarer Tool-Ausgabe stammt, nicht aus Intuition.',
    codeVokuprompt: 'Goal:\nCalculate the minimum number of CI runners needed to keep the pipeline below 12 minutes.\n\nContext:\nUse the six job durations: 8, 11, 7, 5, 14, and 9 minutes.\n\nConstraints:\n- Do not estimate mentally.\n- Use executable code or a repeatable worksheet.\n\nValidation:\n- Show the calculation and raw output.\n- Explain the final runner count briefly.\n\nDone when:\n- The answer is reproducible from the tool output.',
    codeVokupromptDE: 'Ziel:\nDie minimale Anzahl an CI-Runnern berechnen, um die Pipeline unter 12 Minuten zu halten.\n\nKontext:\nDie sechs Job-Dauern 8, 11, 7, 5, 14 und 9 Minuten verwenden.\n\nEinschränkungen:\n- Nicht mental schätzen.\n- Ausführbaren Code oder eine wiederholbare Tabelle verwenden.\n\nValidierung:\n- Berechnung und rohe Ausgabe zeigen.\n- Die finale Runner-Zahl kurz erklären.\n\nFertig wenn:\n- Die Antwort reproduzierbar aus der Tool-Ausgabe hervorgeht.',
    content: 'Repeatable logic belongs in code, scripts, SQL, or spreadsheets. Prompts should tell the model to use the tool and show the result, not to improvise arithmetic in prose.',
    contentDE: 'Wiederholbare Logik gehört in Code, Skripte, SQL oder Tabellen. Prompts sollten dem Modell sagen, das Werkzeug zu verwenden und das Ergebnis zu zeigen – nicht, Arithmetik im Fließtext zu improvisieren.',
  },
  {
    id: 8,
    type: SlideType.COMPARISON,
    icon: 'Braces',
    title: 'Output Must Be Structured and Validated',
    titleDE: 'Ausgabe muss strukturiert und validiert sein',
    subtitle: 'Free-form prose is expensive to review and easy to misread in pipelines.',
    subtitleDE: 'Freier Fließtext ist teuer zu reviewen und in Pipelines leicht misszuverstehen.',
    technique: 'Structured output',
    techniqueDE: 'Strukturierte Ausgabe',
    codeStandard: 'Review this pull request and tell me what matters.',
    codeStandardDE: 'Reviewe diesen Pull Request und sag mir, was wichtig ist.',
    codeOptimized: 'Goal: Review the pull request for shipping risk.\nContext: Inspect the changed files, test results, and CI status.\nConstraints: Cite evidence for every claim and separate facts from assumptions.\nOutput format: Reply only in valid JSON with risk_level, changed_areas, blockers, follow_up_checks, and evidence.\nValidation: Ensure every field is populated or explicitly null.\nDone when: The JSON is valid and every claim points to evidence.',
    codeOptimizedDE: 'Ziel: Den Pull Request auf Auslieferungsrisiko reviewen.\nKontext: Geänderte Dateien, Testergebnisse und CI-Status prüfen.\nEinschränkungen: Für jede Aussage Belege angeben und Fakten von Annahmen trennen.\nAusgabeformat: Nur als gültiges JSON mit risk_level, changed_areas, blockers, follow_up_checks und evidence antworten.\nValidierung: Sicherstellen, dass jedes Feld befüllt oder explizit null ist.\nFertig wenn: Das JSON gültig ist und jede Aussage auf Belege verweist.',
    codeVokuprompt: 'Goal:\nReview the pull request for shipping risk.\n\nContext:\nInspect changed files, test results, and CI status.\n\nConstraints:\n- Separate facts from assumptions.\n- Cite evidence for every claim.\n\nOutput format:\n- Reply only in valid JSON with risk_level, changed_areas, blockers, follow_up_checks, and evidence.\n\nValidation:\n- Verify the JSON is valid and every field is filled or null.\n\nDone when:\n- Every claim points to evidence and the response is machine-checkable.',
    codeVokupromptDE: 'Ziel:\nDen Pull Request auf Auslieferungsrisiko prüfen.\n\nKontext:\nGeänderte Dateien, Testergebnisse und CI-Status inspizieren.\n\nEinschränkungen:\n- Fakten von Annahmen trennen.\n- Für jede Aussage Belege angeben.\n\nAusgabeformat:\n- Nur als gültiges JSON mit risk_level, changed_areas, blockers, follow_up_checks und evidence antworten.\n\nValidierung:\n- Prüfen, dass das JSON gültig ist und jedes Feld befüllt oder null ist.\n\nFertig wenn:\n- Jede Aussage auf Belege verweist und die Antwort maschinenprüfbar ist.',
    content: 'Structure is not aesthetics. Structure is what makes downstream validation, automation, and human review practical.',
    contentDE: 'Struktur ist keine Ästhetik. Struktur macht nachgelagerte Validierung, Automatisierung und menschliches Review überhaupt erst praktikabel.',
  },
  {
    id: 9,
    type: SlideType.COMPARISON,
    icon: 'GitPullRequestArrow',
    title: 'Named Passes, Assumptions, and Reasoning Summaries',
    titleDE: 'Benannte Durchläufe, Annahmen und Begründungszusammenfassungen',
    subtitle: 'Do not ask for hidden chain-of-thought. Ask for checks, assumptions, and concise evidence-backed summaries.',
    subtitleDE: 'Kein verborgenes Chain-of-Thought verlangen. Stattdessen Checks, Annahmen und knappe, belegte Zusammenfassungen fordern.',
    technique: 'Safe reasoning workflow',
    techniqueDE: 'Sicherer Denk-Workflow',
    codeStandard: 'Review this PR and show your chain of thought.',
    codeStandardDE: 'Reviewe diesen PR und zeige deine Chain of Thought.',
    codeOptimized: 'Goal: Review the PR in a way another engineer can verify.\nContext: Use the diff, test output, and touched interfaces.\nConstraints: Do not reveal hidden reasoning. Work in named passes and keep the final report concise.\nOutput format: Sections for Pass 1 API changes, Pass 2 failure modes, Pass 3 test gaps, Assumptions, and Final reasoning summary.\nValidation: Cite evidence for each conclusion.\nDone when: Each pass is complete and the final summary is short enough for handoff.',
    codeOptimizedDE: 'Ziel: Den PR so reviewen, dass ein anderer Engineer ihn verifizieren kann.\nKontext: Diff, Testausgabe und berührte Schnittstellen verwenden.\nEinschränkungen: Keine verborgenen Gedankengänge offenlegen. In benannten Durchläufen arbeiten und den finalen Bericht knapp halten.\nAusgabeformat: Abschnitte für Durchlauf 1 API-Änderungen, Durchlauf 2 Fehlermodi, Durchlauf 3 Testlücken, Annahmen und finale Begründungszusammenfassung.\nValidierung: Für jede Schlussfolgerung Belege angeben.\nFertig wenn: Jeder Durchlauf vollständig ist und die Zusammenfassung kurz genug für eine Übergabe bleibt.',
    codeVokuprompt: 'Goal:\nReview the PR so another engineer can verify the result quickly.\n\nContext:\nUse the diff, test output, and touched interfaces.\n\nConstraints:\n- Do not ask for or reveal hidden chain-of-thought.\n- Work in named passes and keep the final report concise.\n\nOutput format:\n- Pass 1: API changes\n- Pass 2: Failure modes\n- Pass 3: Test gaps\n- Assumptions\n- Final reasoning summary\n\nValidation:\n- Cite evidence for each conclusion.\n\nDone when:\n- Every pass is complete and the final summary is ready for handoff.',
    codeVokupromptDE: 'Ziel:\nDen PR so reviewen, dass ein anderer Engineer das Ergebnis schnell verifizieren kann.\n\nKontext:\nDiff, Testausgabe und berührte Schnittstellen verwenden.\n\nEinschränkungen:\n- Keine verborgenen Gedankengänge verlangen oder offenlegen.\n- In benannten Durchläufen arbeiten und den finalen Bericht knapp halten.\n\nAusgabeformat:\n- Durchlauf 1: API-Änderungen\n- Durchlauf 2: Fehlermodi\n- Durchlauf 3: Testlücken\n- Annahmen\n- Finale Begründungszusammenfassung\n\nValidierung:\n- Für jede Schlussfolgerung Belege angeben.\n\nFertig wenn:\n- Jeder Durchlauf vollständig ist und die finale Zusammenfassung für die Übergabe bereitsteht.',
    content: '“Show your chain of thought” is the wrong operational request. Ask for named passes, explicit assumptions, validation results, and a concise reasoning summary that others can review.',
    contentDE: '„Zeig deine Chain of Thought“ ist die falsche operative Anweisung. Fordere benannte Durchläufe, explizite Annahmen, Validierungsergebnisse und eine knappe Begründungszusammenfassung, die andere reviewen können.',
  },
  {
    id: 10,
    type: SlideType.COMPARISON,
    icon: 'TestTube2',
    title: 'Tests Must Be Witnesses, Not Accomplices',
    titleDE: 'Tests müssen Zeugen sein, nicht Mittäter',
    subtitle: 'A passing test suite is evidence only if the tests challenge the code.',
    subtitleDE: 'Eine bestandene Testsuite ist nur dann Beweis, wenn die Tests den Code herausfordern.',
    technique: 'Test-driven verification',
    techniqueDE: 'Testgetriebene Verifikation',
    codeStandard: 'Write tests for this change and make sure they pass.',
    codeStandardDE: 'Schreib Tests für diese Änderung und stelle sicher, dass sie bestehen.',
    codeOptimized: 'Goal: Verify the change with tests that expose real risk.\nContext: Start from the failing path and compare it with existing regression coverage.\nConstraints: Do not change assertions just to silence failures; fix the code instead.\nValidation: Show the failing test first, then the passing run after the fix.\nDone when: At least one new or improved test proves a previously broken assumption or edge case.',
    codeOptimizedDE: 'Ziel: Die Änderung mit Tests verifizieren, die echtes Risiko aufdecken.\nKontext: Beim fehlschlagenden Pfad starten und mit vorhandener Regressionsabdeckung vergleichen.\nEinschränkungen: Assertions nicht ändern, nur um Fehler zu unterdrücken; stattdessen den Code korrigieren.\nValidierung: Zuerst den fehlschlagenden Test zeigen, dann den erfolgreichen Lauf nach dem Fix.\nFertig wenn: Mindestens ein neuer oder verbesserter Test eine zuvor kaputte Annahme oder einen Edge Case beweist.',
    codeVokuprompt: 'Goal:\nVerify the change with tests that expose real risk.\n\nContext:\nStart from the failing path and compare it with the current regression coverage.\n\nConstraints:\n- Do not change assertions just to silence failures.\n- Fix the code instead of teaching the test to agree.\n\nValidation:\n- Show the failing test first, then the passing run after the fix.\n\nDone when:\n- At least one new or improved test proves a previously broken assumption or edge case.\n\nState update:\n- Record the regression pattern in tests or documentation so the failure stays visible.',
    codeVokupromptDE: 'Ziel:\nDie Änderung mit Tests verifizieren, die echtes Risiko aufdecken.\n\nKontext:\nBeim fehlschlagenden Pfad starten und mit der aktuellen Regressionsabdeckung vergleichen.\n\nEinschränkungen:\n- Assertions nicht ändern, nur um Fehler zu unterdrücken.\n- Den Code korrigieren, statt dem Test Zustimmung beizubringen.\n\nValidierung:\n- Zuerst den fehlschlagenden Test zeigen, dann den erfolgreichen Lauf nach dem Fix.\n\nFertig wenn:\n- Mindestens ein neuer oder verbesserter Test eine zuvor fehlerhafte Annahme oder einen Edge Case beweist.\n\nStatus-Update:\n- Das Regressionsmuster in Tests oder Dokumentation festhalten, damit der Fehler sichtbar bleibt.',
    content: 'Agents often treat tests as paperwork. Strong prompts force tests to act as witnesses: they must expose the defect, not simply confirm whatever currently passes.',
    contentDE: 'Agenten behandeln Tests oft wie Bürokratie. Starke Prompts zwingen Tests dazu, als Zeugen zu handeln: Sie müssen den Fehler sichtbar machen und nicht nur bestätigen, was gerade zufällig besteht.',
  },
  {
    id: 11,
    type: SlideType.PLAYGROUND,
    icon: 'Radar',
    title: 'Playground: Score the Prompt Before You Run It',
    titleDE: 'Playground: Prompt bewerten, bevor du ihn ausführst',
    subtitle: 'Local evaluator for operational prompt quality: no backend, no model call, just contract checks and warnings.',
    subtitleDE: 'Lokaler Evaluator für operative Prompt-Qualität: kein Backend, kein Modellaufruf, nur Vertrags-Checks und Warnungen.',
  },
  {
    id: 12,
    type: SlideType.CONTENT,
    icon: 'BookMarked',
    title: 'Successful Patterns Must Be Written Back',
    titleDE: 'Erfolgreiche Muster müssen zurückgeschrieben werden',
    subtitle: 'A good session should leave the repository easier to use next time.',
    subtitleDE: 'Eine gute Sitzung sollte das Repository für das nächste Mal einfacher nutzbar machen.',
    content: [
      'If a prompt pattern works, encode it into AGENTS.md, Skills, repo docs, tests, or implementation notes.',
      'If a failure mode repeats, turn it into a constraint, validation step, or stopping condition.',
      'Do not trust session memory. Persist the learning where the next engineer or agent will actually find it.',
      'Operational prompting matures when successful behavior becomes repo convention instead of tribal knowledge.',
    ],
    contentDE: [
      'Wenn ein Prompt-Muster funktioniert, in AGENTS.md, Skills, Repo-Dokumentation, Tests oder Implementation Notes festhalten.',
      'Wenn ein Fehlermodus sich wiederholt, ihn in eine Einschränkung, einen Validierungsschritt oder eine Abbruchbedingung verwandeln.',
      'Nicht auf Sitzungs-Gedächtnis vertrauen. Das Gelernte dort persistieren, wo der nächste Engineer oder Agent es wirklich findet.',
      'Operatives Prompting reift, wenn erfolgreiches Verhalten zur Repo-Konvention statt zu implizitem Wissen wird.',
    ],
  },
  {
    id: 13,
    type: SlideType.CONTENT,
    icon: 'Workflow',
    title: 'LLM Control Loop',
    titleDE: 'LLM-Kontrollschleife',
    subtitle: 'Reusable structure for handoffs, retries, reviews, and coding-agent work.',
    subtitleDE: 'Wiederverwendbare Struktur für Übergaben, Wiederholungen, Reviews und Coding-Agent-Arbeit.',
    content: [
      'Goal: What should change?',
      'Context: Which files, examples, logs, specs, screenshots, or constraints matter?',
      'Constraints: What must not change?',
      'Validation: Which checks prove correctness?',
      'Done when: What exact condition allows the agent to stop?',
      'State update: What should be written back into AGENTS.md, Skills, docs, tests, or implementation notes?',
    ],
    contentDE: [
      'Ziel: Was soll sich ändern?',
      'Kontext: Welche Dateien, Beispiele, Logs, Spezifikationen, Screenshots oder Einschränkungen sind relevant?',
      'Einschränkungen: Was darf sich nicht ändern?',
      'Validierung: Welche Checks beweisen Korrektheit?',
      'Fertig wenn: Welche exakte Bedingung erlaubt dem Agenten zu stoppen?',
      'Status-Update: Was sollte in AGENTS.md, Skills, Doku, Tests oder Implementation Notes zurückgeschrieben werden?',
    ],
  },
  {
    id: 14,
    type: SlideType.END,
    icon: 'Lightbulb',
    title: 'Final Thesis',
    titleDE: 'Abschlussthese',
    subtitle: 'Good prompts are operational contracts, not magic sentences.',
    subtitleDE: 'Gute Prompts sind operative Verträge, keine magischen Sätze.',
    content: [
      'Good prompts do not simulate expertise. They allocate attention, constrain behavior, demand proof, and define when the work is done.',
      'When the task matters, ask for evidence: raw output, screenshots, cited files, reproducible tool runs, or failing-then-passing tests.',
      'When something works, encode it into the repository so the next session starts from a better floor.',
      'That is how LLM use becomes operational instead of theatrical.',
    ],
    contentDE: [
      'Gute Prompts simulieren keine Expertise. Sie lenken Aufmerksamkeit, begrenzen Verhalten, fordern Beweise und definieren, wann die Arbeit fertig ist.',
      'Wenn die Aufgabe wichtig ist, Belege verlangen: rohe Ausgabe, Screenshots, zitierte Dateien, reproduzierbare Tool-Läufe oder zuerst-fehlschlagende-dann-bestehende Tests.',
      'Wenn etwas funktioniert, es im Repository festhalten, damit die nächste Sitzung auf einer besseren Basis startet.',
      'So wird LLM-Nutzung operativ statt theatralisch.',
    ],
  },
];


export const SERVICE_OPS_SLIDES: SlideData[] = [
  {
    id: 1,
    type: SlideType.TITLE,
    icon: 'ShieldCheck',
    title: 'Operational Prompting for Service Operations',
    titleDE: 'Operatives Prompting für Service Operations',
    subtitle: 'Good service prompts do not create longer tickets. They prepare safe operational work by structuring text, evidence, questions, handoffs, checklists, and write-back drafts.',
    subtitleDE: 'Gute Service-Prompts erzeugen keine längeren Tickets. Sie bereiten sichere operative Arbeit vor: durch Struktur, Evidenz, Fragen, Übergaben, Checklisten und Write-back-Entwürfe.',
  },

  {
    id: 2,
    type: SlideType.COMPARISON,
    icon: 'FileCheck2',
    title: 'Tickets Are Operational Records, Not Chat Messages',
    titleDE: 'Tickets sind operative Nachweise, keine Chat-Nachrichten',
    subtitle: 'Ticket-as-contract prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Ticket-as-contract prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Please clean up this ticket:\n\n"Anna needs access to the reporting folder today. Max has it too. Month-end is blocked. Please add urgency and mention that her manager said it is okay."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nTurn the raw ticket text into an execution-ready ticket summary without hiding missing approval or scope gaps.\n\nInput:\nUse only this provided ticket text:\n"Anna needs access to the reporting folder today. Max has it too. Month-end is blocked. Please add urgency and mention that her manager said it is okay."\n\nConstraints:\nDo not invent approval, resource owner, group name, access level, or business impact. Do not treat "Max has it too" as proof that the same access is valid. Separate facts from assumptions.\n\nValidation:\nCheck whether the ticket contains target user, target resource, access level, requester, approval source, business reason, urgency basis, and missing owner approval.\n\nOutput format:\nReturn sections for Clean Ticket Summary, Facts, Assumptions, Missing Information, Risk Notes, Questions for Requester, and Suggested Ticket Update.\n\nDone when:\nThe ticket is clearer without making the request look more approved or safer than the provided text supports.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: asks for cleanup without defining clean, may polish unsafe assumptions, preserves “Max has it too” as approval-like evidence, fails to separate facts from gaps, and can make a blocked ticket look ready. Lesson: The LLM is not granting access. It is improving ticket quality while preserving uncertainty and missing evidence.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 3,
    type: SlideType.COMPARISON,
    icon: 'LockKeyhole',
    title: 'Uncontrolled Requests Create Unsafe Work',
    titleDE: 'Unkontrollierte Requests erzeugen unsichere Arbeit',
    subtitle: 'Constraint prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Constraint prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Review this login ticket and suggest what to do:\n\n"User cannot log in since this morning. Might be locked. Maybe reset the password or unlock the account. The user needs access urgently because accounting closes today."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nReview the provided login ticket text and identify safe next information needs.\n\nInput:\nUse only this ticket text:\n"User cannot log in since this morning. Might be locked. Maybe reset the password or unlock the account. The user needs access urgently because accounting closes today."\n\nConstraints:\nDo not recommend password reset, account unlock, group changes, or production changes without provided policy/runbook permission and evidence. Do not treat "might be locked" as a fact.\n\nValidation:\nIdentify facts, assumptions, missing evidence, unsafe suggested actions, and the minimum information a human operator needs before acting.\n\nOutput format:\nReturn sections for Facts, Assumptions, Unsafe Action Risks, Missing Information, Questions for Requester, Operator Checklist, and Safe Ticket Reply.\n\nDone when:\nA human operator can see what is known, what is guessed, and what must be checked before any account action.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: invites action recommendations without a policy boundary, mixes guesses with facts, may recommend reset or unlock without evidence, skips missing information, and treats urgency as enough context. Lesson: Constraints make the LLM useful as a reviewer and structuring assistant, not as an imaginary account admin.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 4,
    type: SlideType.CONTENT,
    icon: 'ClipboardList',
    title: 'Goal, Input, Constraints, Done-When',
    titleDE: 'Ziel, Input, Einschränkungen, Fertig-wenn',
    subtitle: 'Contract prompting is the reusable framework for LLM-suitable service operations support work.',
    subtitleDE: 'Contract Prompting ist das wiederverwendbare Framework für LLM-geeignete Service-Operations-Unterstützung.',
    content: [
      'Goal: What should be rewritten, extracted, reviewed, compared, drafted, or prepared?',
      'Input: Which ticket text, logs, command output, screenshots, policy excerpt, runbook excerpt, or closure notes are provided?',
      'Constraints: What must not be invented, approved, changed, closed, or treated as fact?',
      'Validation: Which checks prove the output preserves evidence and exposes gaps?',
      'Output format: What structure is needed for a human operator, requester, approver, or next support team?',
      'Done when: What exact condition makes the draft, checklist, handoff, or update ready for human use?',
      'Write-back: What should be added to the ticket, KB, runbook draft, or known-error candidate?',
    ],
    contentDE: [
      'Ziel: Was soll umgeschrieben, extrahiert, geprüft, verglichen, entworfen oder vorbereitet werden?',
      'Input: Welche Tickettexte, Logs, Command Outputs, Screenshots, Policies, Runbooks oder Abschlussnotizen liegen vor?',
      'Einschränkungen: Was darf nicht erfunden, genehmigt, geändert, geschlossen oder als Fakt behandelt werden?',
      'Validierung: Welche Checks beweisen, dass Evidenz erhalten bleibt und Lücken sichtbar werden?',
      'Ausgabeformat: Welche Struktur braucht ein Operator, Requester, Approver oder das nächste Support-Team?',
      'Fertig wenn: Welche exakte Bedingung macht Entwurf, Checkliste, Übergabe oder Update menschlich nutzbar?',
      'Write-back: Was gehört ins Ticket, den KB-Entwurf, Runbook-Entwurf oder Known-Error-Kandidaten?',
    ],
  },

  {
    id: 5,
    type: SlideType.COMPARISON,
    icon: 'Activity',
    title: 'Incidents Need Evidence Before Action',
    titleDE: 'Incidents brauchen Evidenz vor Aktionen',
    subtitle: 'Evidence-first prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Evidence-first prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Summarize this incident and tell us whether we should restart the API:\n\nTicket:\n"API timeout started again after lunch. It happened last month too."\n\nMonitoring note:\n"13:05-13:22 increased p95 latency. Error rate normal. No deployment today."\n\nLog excerpt:\n"13:08 upstream timeout to payment-service"\n"13:10 retry succeeded"\n"13:14 upstream timeout to payment-service"',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nSummarize the provided incident evidence and prepare a safe investigation note for the ticket.\n\nInput:\nUse only the provided ticket text, monitoring note, and log excerpt.\n\nConstraints:\nDo not recommend restart or production mitigation as a final action. Do not infer root cause beyond the provided evidence. Separate observed symptoms from possible causes.\n\nValidation:\nCheck whether the evidence contains timeline, affected service, error rate, latency impact, deployment context, recurring pattern, and missing data.\n\nOutput format:\nReturn sections for Timeline, Observed Evidence, What This Evidence Supports, What It Does Not Prove, Missing Checks, Suggested Next Investigation Steps, and Ticket Update Text.\n\nDone when:\nThe ticket has an evidence-based summary that helps a human operator decide the next safe action.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: asks for an operational decision from limited evidence, jumps toward restart, blurs symptom/evidence/missing data, and may overstate what the snippets prove. Lesson: The LLM can preserve and structure evidence. It should not pretend limited text is enough to authorize mitigation.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 6,
    type: SlideType.COMPARISON,
    icon: 'UserCheck',
    title: 'Access Requests Need Approval Boundaries',
    titleDE: 'Access Requests brauchen Genehmigungsgrenzen',
    subtitle: 'Policy-bound prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Policy-bound prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Check whether this request is okay:\n\nTicket:\n"Anna moved to controlling and needs the same finance access as Max. Her manager approved it. Please process today."\n\nPolicy excerpt:\n"Finance report folder access requires approval from the resource owner. Access must be granted through the least-privilege AD group matching the requested resource and access level. Access must not be copied from another user as the only evidence."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nCompare the provided access request against the provided policy excerpt and identify whether the ticket is ready for human processing.\n\nInput:\nUse only the ticket text and policy excerpt provided.\n\nConstraints:\nDo not approve or reject the request as a final authority. Do not invent owner approval, group names, or access levels. Do not treat another user’s access as sufficient evidence.\n\nValidation:\nCheck the ticket against each policy requirement: resource owner approval, least-privilege group, requested resource, access level, and no access-copying as sole evidence.\n\nOutput format:\nReturn sections for Policy Requirements, Evidence Present, Evidence Missing, Risk Notes, Questions for Requester, and Suggested Ticket Update.\n\nDone when:\nA human operator can clearly see whether the request is ready, blocked, or missing required information.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: is underspecified, may collapse policy review into yes/no, ignore missing owner approval, treat manager approval as sufficient, and fail to produce useful ticket text. Lesson: The LLM is useful for policy comparison and gap detection, not for granting permissions.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 7,
    type: SlideType.COMPARISON,
    icon: 'SearchCheck',
    title: 'Facts Require Retrieval from Systems',
    titleDE: 'Fakten erfordern Retrieval aus Systemen',
    subtitle: 'Retrieval prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Retrieval prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Please review this mailbox issue and explain what might be wrong:\n\nTicket:\n"The department says emails are not arriving in the shared mailbox."\n\nProvided mailbox output:\nPrimarySmtpAddress: invoices@example.org\nForwardingAddress: accounting-archive@example.org\nDeliverToMailboxAndForward: false\n\nProvided distribution list output:\nDL invoices-team@example.org members:\n- anna@example.org\n- max@example.org',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nReview the provided mailbox and distribution-list output and identify what can be concluded safely.\n\nInput:\nUse only the ticket text and provided command output.\n\nConstraints:\nDo not claim the configuration is wrong unless the expected standard is provided. Do not invent mailbox policy. Do not suggest changing forwarding or distribution list membership without an approved expected state.\n\nValidation:\nSeparate current observed state from missing expected state. Identify which facts are supported by the output and which checks are still needed.\n\nOutput format:\nReturn sections for Current Observed State, Supported Facts, Missing Expected State, Possible Questions, Risk Notes, and Ticket Update Text.\n\nDone when:\nThe ticket clearly documents what the provided output shows and what cannot be concluded yet.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: asks for explanation without expected state, may infer correctness without a standard, can overlook that output alone is insufficient, and may fail to ask for the missing mailbox standard. Lesson: Retrieval prompting should make evidence visible and bounded. It should not turn partial output into fake certainty.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 8,
    type: SlideType.COMPARISON,
    icon: 'TerminalSquare',
    title: 'Repeatable Checks Require Tools or Scripts',
    titleDE: 'Wiederholbare Checks brauchen Tools oder Skripte',
    subtitle: 'Tool-use prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Tool-use prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Tell the service desk how to check whether a user has the right AD groups and mailbox settings.',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nCreate a read-only verification checklist for a human operator.\n\nContext:\nThe operator needs to verify user account status, group membership, mailbox aliases, forwarding, and distribution-list membership before changing anything.\n\nConstraints:\nOnly propose read-only checks. Do not include commands that modify users, groups, mailbox settings, or distribution lists. Mark placeholders clearly.\n\nValidation:\nFor each check, define the purpose, required input, expected evidence, and what output should be pasted back into the ticket.\n\nOutput format:\nReturn a table with columns: Check, Purpose, Placeholder Input, Read-Only Command or Manual Step, Evidence to Paste, and Follow-Up If Missing.\n\nDone when:\nThe operator has a reproducible verification checklist that does not perform changes.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: is too broad, may suggest unsafe write commands, fails to distinguish read-only checks from changes, leaves expected output undefined, and is not ticket-ready. Lesson: The LLM can draft a safe checklist or command plan. The human or approved tool performs the actual checks.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 9,
    type: SlideType.COMPARISON,
    icon: 'MessagesSquare',
    title: 'Output Must Be Structured for Handoff',
    titleDE: 'Output muss für Übergaben strukturiert sein',
    subtitle: 'Structured-output prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Structured-output prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Write an escalation for this ticket:\n\n"The user still cannot access the report. We checked some things. It might be network or permissions. The user is annoyed and wants it fixed today."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nDraft an escalation note from the provided ticket notes without inventing evidence.\n\nInput:\nUse only these notes:\n"The user still cannot access the report. We checked some things. It might be network or permissions. The user is annoyed and wants it fixed today."\n\nConstraints:\nDo not invent checks, timestamps, systems, teams, priority, or root cause. Do not present guesses as facts. Keep missing information visible.\n\nValidation:\nIdentify whether the notes include impact, timeline, attempted steps, evidence, current blocker, suspected target team, and requested action.\n\nOutput format:\nReturn sections for Escalation Draft, Facts Available, Missing Information, Assumptions to Avoid, Questions Before Escalation, and Suggested Ticket Update.\n\nDone when:\nThe escalation draft is usable only if clearly marked gaps are resolved, instead of hiding weak evidence behind polished wording.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: may polish vague notes, invent completed checks, turn annoyance into priority, escalate without a clear question, and hide missing evidence. Lesson: Structured output helps prevent polished nonsense from becoming someone else’s problem.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 10,
    type: SlideType.COMPARISON,
    icon: 'ShieldAlert',
    title: 'Validation Must Prove the Next Action Is Safe',
    titleDE: 'Validierung muss beweisen, dass die nächste Aktion sicher ist',
    subtitle: 'Validation prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Validation prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Improve this change approval text:\n\n"The vendor recommends changing timeout from 30s to 60s tonight. It should fix the API errors. Rollback is changing it back. The change is small."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nReview the provided change approval text for readiness gaps before rewriting it.\n\nInput:\nUse only this change text:\n"The vendor recommends changing timeout from 30s to 60s tonight. It should fix the API errors. Rollback is changing it back. The change is small."\n\nConstraints:\nDo not make the change sound approved or low-risk unless evidence is present. Separate vendor claim from verified local evidence. Do not invent rollback testing, impact analysis, approvals, or post-change checks.\n\nValidation:\nCheck for affected systems, observed error evidence, user impact, approval status, tested rollback, implementation steps, maintenance window, dependencies, and post-change validation.\n\nOutput format:\nReturn sections for Verified Facts, Unsupported Claims, Missing Readiness Evidence, Risk Notes, Questions Before Approval, and Safer Draft Text.\n\nDone when:\nThe revised text improves clarity without hiding that the change is not approval-ready.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: asks for better wording instead of readiness review, may make unsafe change text sound approved, hides rollback gaps, accepts vendor claims as facts, and treats “small” as risk assessment. Lesson: Validation prompting makes the LLM challenge unsafe wording before it makes the wording prettier. Humanity occasionally deserves that mercy.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 11,
    type: SlideType.PLAYGROUND,
    icon: 'Radar',
    title: 'Playground: Score the Request Before You Run It',
    titleDE: 'Playground: Request prüfen, bevor du ihn nutzt',
    subtitle: 'Local evaluator for LLM-suitable service-operation support work: operational quality, not prompt length.',
    subtitleDE: 'Lokaler Evaluator für LLM-geeignete Service-Operations-Unterstützung: operative Qualität, nicht Prompt-Länge.',
  },

  {
    id: 12,
    type: SlideType.COMPARISON,
    icon: 'BookOpenCheck',
    title: 'Successful Patterns Must Become Runbooks',
    titleDE: 'Erfolgreiche Muster müssen zu Runbooks werden',
    subtitle: 'Write-back prompting: LLMs should prepare the work, not pretend they performed the work.',
    subtitleDE: 'Service-Operations-Prompting: LLMs sollen die Arbeit vorbereiten, nicht so tun, als hätten sie sie ausgeführt.',
    technique: 'Write-back prompting',
    techniqueDE: 'Service-Operations-Prompting',
    codeStandard: 'Make a KB article from these closure notes:\n\n"Restarted job queue. Emails went out again. Same as last time. Tell people to restart queue if it happens again."',
    codeStandardDE: 'Bitte prüfe den bereitgestellten Service-Operations-Request. Nutze nur sichtbare Ticketdaten und formuliere keine operative Aktion als bereits ausgeführt.',
    codeOptimized: 'Goal:\nTurn the closure notes into a draft KB article without overstating certainty.\n\nInput:\nUse only these closure notes:\n"Restarted job queue. Emails went out again. Same as last time. Tell people to restart queue if it happens again."\n\nConstraints:\nDo not present restart as the approved standard fix unless the notes prove it. Mark missing evidence and approval gaps. Separate confirmed observation from proposed procedure.\n\nValidation:\nCheck whether the notes include symptoms, affected system, detection method, evidence before restart, approved restart condition, validation after restart, rollback or stop condition, and escalation owner.\n\nOutput format:\nReturn a KB draft with sections for Symptoms, Confirmed Observations, Missing Evidence, Safe Preconditions, Draft Procedure, Stop Conditions, Validation, Escalation Path, and Related Tickets.\n\nDone when:\nThe KB draft is useful for review without turning an unverified workaround into policy.',
    codeOptimizedDE: 'Ziel:\nBereite den bereitgestellten Service-Operations-Fall für menschliche Bearbeitung vor.\n\nInput:\nNutze nur die bereitgestellten Tickettexte, Outputs, Logs, Policies oder Notizen.\n\nEinschränkungen:\nErfinde keine Evidenz, Genehmigung, Systemzugriffe, Änderungen oder Abschlüsse. Das LLM soll Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.\n\nValidierung:\nTrenne Fakten, Annahmen, fehlende Informationen, Risiken und offene Fragen.\n\nAusgabeformat:\nGib eine strukturierte, ticketfähige Antwort mit Fakten, Lücken, Fragen, Risikohinweisen und Entwurfstext zurück.\n\nFertig wenn:\nEin menschlicher Operator die nächsten sicheren Schritte und fehlende Evidenz klar erkennen kann.',
    content: 'Risk: may turn a fragile workaround into official guidance, lacks symptoms/evidence/stop conditions/escalation path, mixes fix and assumption, and may recommend restart without safety boundaries. Lesson: The LLM can draft knowledge safely, but it must preserve uncertainty instead of laundering guesses into documentation.',
    contentDE: 'Risiko: Der schwache Prompt kann fehlende Evidenz überdecken, Annahmen polieren oder operative Aktionen nahelegen. Lektion: Das LLM soll bereitgestellte Informationen strukturieren, Lücken sichtbar machen und sichere Entwürfe vorbereiten, nicht Zugriff, Änderungen oder Mitigationen ausführen.',
  },

  {
    id: 13,
    type: SlideType.CONTENT,
    icon: 'Workflow',
    title: 'Service Operations Control Loop',
    titleDE: 'Service Operations Control Loop',
    subtitle: 'Input → Extract → Bound → Draft → Validate → Handoff → Write-back.',
    subtitleDE: 'Input → Extrahieren → Begrenzen → Entwerfen → Validieren → Übergeben → Write-back.',
    content: [
      'Input: What ticket text, logs, command output, screenshots, policy, runbook, or closure notes are provided?',
      'Extract: What facts, assumptions, missing information, risks, and unsafe requested actions are visible?',
      'Bound: What must the LLM not invent, approve, execute, close, or treat as verified?',
      'Draft: What ticket update, requester questions, checklist, escalation note, or KB/runbook draft should be prepared?',
      'Validation: Which checks prove the draft preserves uncertainty and exposes gaps?',
      'Handoff: What structure does the human operator, approver, or next support team need?',
      'Write-back: What belongs in the ticket, knowledge base, runbook draft, or known-error candidate?',
    ],
    contentDE: [
      'Input: Welche Tickettexte, Logs, Command Outputs, Screenshots, Policies, Runbooks oder Abschlussnotizen liegen vor?',
      'Extrahieren: Welche Fakten, Annahmen, fehlenden Informationen, Risiken und unsicheren angefragten Aktionen sind sichtbar?',
      'Begrenzen: Was darf das LLM nicht erfinden, genehmigen, ausführen, schließen oder als verifiziert behandeln?',
      'Entwerfen: Welches Ticket-Update, welche Requester-Fragen, Checkliste, Eskalationsnotiz oder welcher KB-/Runbook-Entwurf soll vorbereitet werden?',
      'Validierung: Welche Checks beweisen, dass der Entwurf Unsicherheit erhält und Lücken sichtbar macht?',
      'Übergabe: Welche Struktur braucht der menschliche Operator, Approver oder das nächste Support-Team?',
      'Write-back: Was gehört ins Ticket, in die Knowledge Base, den Runbook-Entwurf oder den Known-Error-Kandidaten?',
    ],
  },
  {
    id: 14,
    type: SlideType.END,
    icon: 'Lightbulb',
    title: 'Final Thesis',
    titleDE: 'Abschlussthese',
    subtitle: 'The LLM should prepare the work, not pretend it performed the work.',
    subtitleDE: 'Das LLM soll die Arbeit vorbereiten, nicht so tun, als hätte es sie ausgeführt.',
    content: [
      'Good service-operations prompts do not create longer tickets. They create safer prepared work.',
      'They structure provided evidence, separate facts from assumptions, detect unsafe requests, draft questions and handoffs, prepare read-only checklists, and turn resolved notes into reviewable KB or runbook drafts.',
      'They do not frame the model as a hidden operator with invisible access to AD, mailboxes, monitoring, or production systems.',
    ],
    contentDE: [
      'Gute Service-Operations-Prompts erzeugen keine längeren Tickets. Sie erzeugen sicherer vorbereitete Arbeit.',
      'Sie strukturieren bereitgestellte Evidenz, trennen Fakten von Annahmen, erkennen unsichere Requests, entwerfen Fragen und Übergaben, bereiten Read-only-Checklisten vor und verwandeln Abschlussnotizen in prüfbare KB- oder Runbook-Entwürfe.',
      'Sie rahmen das Modell nicht als versteckten Operator mit unsichtbarem Zugriff auf AD, Mailboxen, Monitoring oder Produktionssysteme.',
    ],
  },
];

export const GUIDE_SLIDES: Record<GuideMode, SlideData[]> = {
  coding: CODING_SLIDES,
  serviceOps: SERVICE_OPS_SLIDES,
};
