import { GUIDE_SLIDES as BASE_GUIDE_SLIDES } from './constants';
import { GuideMode, SlideData } from './types';

const OVERRIDES: Record<GuideMode, Record<number, Partial<SlideData>>> = {
  coding: {
    1: {
      title: 'Operational Prompting for Real IT Work',
      titleDE: 'Operatives Prompting für echte IT-Arbeit',
      subtitle: 'Task-fit prompts for engineering, architecture, data, operations, documentation, support, and technical decisions. More text is not the goal.',
      subtitleDE: 'Passende Prompts für Engineering, Architektur, Daten, Betrieb, Dokumentation, Support und technische Entscheidungen. Mehr Text ist nicht das Ziel.',
    },
    2: {
      title: 'Useful, Fast, and Still Unreliable Without Control',
      titleDE: 'Nützlich, schnell und ohne Kontrolle trotzdem unzuverlässig',
      content: [
        'Models can draft, summarise, compare, transform, navigate systems, and prepare decisions across IT work.',
        'They remain weak at silent assumptions, stale facts, arithmetic, missing system access, and stopping at the right boundary.',
        'Prompt quality is task fit, not length. Add only the context, constraints, evidence, and stopping conditions the task actually needs.',
        'A one-line request can be sufficient for a simple transformation. A risky production change needs a stronger operational contract.',
      ],
      contentDE: [
        'Modelle können entwerfen, zusammenfassen, vergleichen, transformieren, Systeme erschließen und Entscheidungen für unterschiedliche IT-Arbeit vorbereiten.',
        'Sie bleiben schwach bei stillen Annahmen, veralteten Fakten, Arithmetik, fehlendem Systemzugriff und beim Stoppen an der richtigen Grenze.',
        'Prompt-Qualität bedeutet Aufgabenpassung, nicht Länge. Ergänze nur Kontext, Grenzen, Evidenz und Abbruchbedingungen, die die Aufgabe tatsächlich braucht.',
        'Für eine einfache Transformation kann ein Einzeiler reichen. Eine riskante Produktionsänderung braucht einen stärkeren operativen Vertrag.',
      ],
    },
    3: {
      title: 'The Smallest Sufficient Prompt Wins',
      titleDE: 'Der kleinste ausreichende Prompt gewinnt',
      subtitle: 'A longer prompt can still be vague, repetitive, and operationally useless.',
      subtitleDE: 'Ein längerer Prompt kann trotzdem vage, wiederholend und operativ nutzlos sein.',
      technique: 'Task-fit prompting',
      techniqueDE: 'Aufgabenpassendes Prompting',
      codeStandard: 'Please perform a very detailed, comprehensive, professional, and careful review of our nightly backup situation. Think through every possible issue, cover all relevant technical and organisational aspects, be extremely thorough, do not miss anything important, explain everything clearly, and provide the best possible answer for management and the technical team.',
      codeStandardDE: 'Bitte führe eine sehr detaillierte, umfassende, professionelle und sorgfältige Prüfung unserer nächtlichen Backup-Situation durch. Denke über jedes mögliche Problem nach, decke alle relevanten technischen und organisatorischen Aspekte ab, sei extrem gründlich, übersehe nichts Wichtiges, erkläre alles verständlich und liefere die bestmögliche Antwort für Management und Technik.',
      codeOptimized: 'Assess restore readiness from the attached backup report and last restore-test log. Separate verified facts, gaps, and assumptions. Return the three highest risks plus the next evidence needed. Do not claim recoverability without a successful restore test.',
      codeOptimizedDE: 'Bewerte die Wiederherstellungsbereitschaft anhand des beigefügten Backup-Reports und des letzten Restore-Test-Logs. Trenne verifizierte Fakten, Lücken und Annahmen. Nenne die drei höchsten Risiken sowie die als Nächstes benötigte Evidenz. Behaupte keine Wiederherstellbarkeit ohne erfolgreichen Restore-Test.',
      codeVokuprompt: undefined,
      codeVokupromptDE: undefined,
      content: 'The shorter version is better because it names the evidence, decision boundary, output, and forbidden conclusion. The longer version merely spends tokens asking for greatness, humanity’s most renewable resource.',
      contentDE: 'Die kürzere Version ist besser, weil sie Evidenz, Entscheidungsgrenze, Ausgabe und verbotene Schlussfolgerung benennt. Die längere Version verbraucht nur Tokens für den Wunsch nach Großartigkeit, offenbar eine unerschöpfliche Ressource.',
    },
    4: {
      title: 'Use Only the Contract Fields the Task Needs',
      titleDE: 'Nutze nur die Vertragsfelder, die die Aufgabe braucht',
      subtitle: 'Goal, context, constraints, validation, output, and done-when are tools, not mandatory ceremony.',
      subtitleDE: 'Ziel, Kontext, Einschränkungen, Validierung, Ausgabe und Fertig-wenn sind Werkzeuge, keine Pflichtzeremonie.',
      content: [
        'Simple task: state the transformation and desired output. Stop there.',
        'Ambiguous task: add the minimum context that resolves the ambiguity.',
        'Risky task: add boundaries, evidence requirements, validation, and a stopping condition.',
        'Long-running task: add checkpoints and write-back so work remains resumable.',
        'Delete instructions that do not change the expected behavior. Prompt weight is not prompt quality.',
      ],
      contentDE: [
        'Einfache Aufgabe: Transformation und gewünschte Ausgabe benennen. Dann aufhören.',
        'Mehrdeutige Aufgabe: nur den Kontext ergänzen, der die Mehrdeutigkeit auflöst.',
        'Riskante Aufgabe: Grenzen, Evidenzpflicht, Validierung und Abbruchbedingung ergänzen.',
        'Länger laufende Aufgabe: Checkpoints und Write-back ergänzen, damit die Arbeit fortsetzbar bleibt.',
        'Anweisungen löschen, die das erwartete Verhalten nicht verändern. Prompt-Gewicht ist keine Prompt-Qualität.',
      ],
    },
    7: {
      title: 'Repeatable Decisions Require Tools, Not More Prose',
      titleDE: 'Wiederholbare Entscheidungen brauchen Tools, nicht mehr Prosa',
      subtitle: 'Capacity, cost, inventory, scheduling, and risk calculations belong in executable logic.',
      subtitleDE: 'Kapazitäts-, Kosten-, Inventar-, Termin- und Risikoberechnungen gehören in ausführbare Logik.',
      technique: 'Tool-backed decision support',
      techniqueDE: 'Tool-gestützte Entscheidungsunterstützung',
      codeStandard: 'Estimate whether our storage will last until the next budget cycle and explain your reasoning in detail.',
      codeStandardDE: 'Schätze, ob unser Speicher bis zur nächsten Budgetrunde reicht, und erkläre deine Überlegungen ausführlich.',
      codeOptimized: 'Using the attached 90-day storage-growth export, calculate the exhaustion date with a reproducible script or spreadsheet. Show assumptions, raw result, and sensitivity at ±20% growth. Do not extrapolate from prose alone.',
      codeOptimizedDE: 'Berechne anhand des beigefügten 90-Tage-Exports zum Speicherwachstum das Erschöpfungsdatum mit einem reproduzierbaren Skript oder einer Tabelle. Zeige Annahmen, Rohresultat und Sensitivität bei ±20 % Wachstum. Nicht allein aus Fließtext extrapolieren.',
      codeVokuprompt: undefined,
      codeVokupromptDE: undefined,
      content: 'IT includes capacity, infrastructure, identity, data, operations, architecture, governance, and service decisions. When logic must repeat, move it into a tool and make the prompt request evidence.',
      contentDE: 'IT umfasst Kapazität, Infrastruktur, Identität, Daten, Betrieb, Architektur, Governance und Service-Entscheidungen. Wenn Logik wiederholbar sein muss, gehört sie in ein Tool und der Prompt muss Evidenz verlangen.',
    },
    12: {
      title: 'Successful Patterns Must Be Written Back Where Work Lives',
      titleDE: 'Erfolgreiche Muster müssen dort zurückgeschrieben werden, wo Arbeit stattfindet',
      subtitle: 'Repositories are one destination among runbooks, service maps, architecture records, knowledge bases, and operating procedures.',
      subtitleDE: 'Repositories sind nur ein Ziel neben Runbooks, Service Maps, Architekturentscheidungen, Wissensdatenbanken und Betriebsverfahren.',
      content: [
        'Write software-specific learning into tests, code, AGENTS.md, or repository documentation.',
        'Write operational learning into runbooks, known-error records, monitoring rules, and recovery procedures.',
        'Write architectural learning into decision records, service maps, interfaces, and ownership documentation.',
        'Write service-management learning into policies, workflows, knowledge, measures, and improvement backlogs.',
        'Persist only verified, reusable learning. Session memory and polished guesses are not governance.',
      ],
      contentDE: [
        'Software-spezifisches Lernen gehört in Tests, Code, AGENTS.md oder Repo-Dokumentation.',
        'Operatives Lernen gehört in Runbooks, Known-Error-Einträge, Monitoring-Regeln und Recovery-Verfahren.',
        'Architektur-Lernen gehört in Decision Records, Service Maps, Schnittstellen- und Ownership-Dokumentation.',
        'Service-Management-Lernen gehört in Policies, Workflows, Wissen, Kennzahlen und Verbesserungs-Backlogs.',
        'Nur verifiziertes, wiederverwendbares Lernen persistieren. Sitzungs-Gedächtnis und polierte Vermutungen sind keine Governance.',
      ],
    },
    13: {
      title: 'Task-Fit LLM Control Loop',
      titleDE: 'Aufgabenpassende LLM-Kontrollschleife',
      subtitle: 'Start small. Add control only when ambiguity, risk, duration, or handoff requires it.',
      subtitleDE: 'Klein anfangen. Kontrolle nur ergänzen, wenn Mehrdeutigkeit, Risiko, Dauer oder Übergabe sie erfordern.',
      content: [
        'Goal: What useful outcome is needed?',
        'Evidence: Which files, data, logs, policies, diagrams, or observations matter?',
        'Boundaries: What must not be invented, changed, approved, or treated as verified?',
        'Method: Is prose enough, or does the task require retrieval, code, calculation, or a connected system?',
        'Validation: What proves the result is usable?',
        'Stop and write back: When is the task complete, and where does durable learning belong?',
      ],
      contentDE: [
        'Ziel: Welches nutzbare Ergebnis wird benötigt?',
        'Evidenz: Welche Dateien, Daten, Logs, Policies, Diagramme oder Beobachtungen sind relevant?',
        'Grenzen: Was darf nicht erfunden, geändert, genehmigt oder als verifiziert behandelt werden?',
        'Methode: Reicht Text oder braucht die Aufgabe Retrieval, Code, Berechnung oder ein verbundenes System?',
        'Validierung: Was beweist, dass das Ergebnis nutzbar ist?',
        'Stoppen und zurückschreiben: Wann ist die Aufgabe fertig und wohin gehört dauerhaftes Lernen?',
      ],
    },
    14: {
      subtitle: 'Good prompts are the smallest operational contracts that make the task safe and verifiable.',
      subtitleDE: 'Gute Prompts sind die kleinsten operativen Verträge, die eine Aufgabe sicher und prüfbar machen.',
      content: [
        'More text is not more control. Relevant evidence, boundaries, tools, validation, and stopping conditions are control.',
        'The right prompt may be one sentence or one page. Its size follows the task, not the presenter’s enthusiasm.',
        'IT work is broader than code, so examples and write-back must include systems, services, operations, architecture, data, governance, and people.',
        'That is how LLM use becomes operational instead of theatrical.',
      ],
      contentDE: [
        'Mehr Text ist nicht mehr Kontrolle. Relevante Evidenz, Grenzen, Tools, Validierung und Abbruchbedingungen sind Kontrolle.',
        'Der passende Prompt kann ein Satz oder eine Seite lang sein. Seine Größe folgt der Aufgabe, nicht der Begeisterung des Vortragenden.',
        'IT-Arbeit ist breiter als Code. Beispiele und Write-back müssen daher Systeme, Services, Betrieb, Architektur, Daten, Governance und Menschen einbeziehen.',
        'So wird LLM-Nutzung operativ statt theatralisch.',
      ],
    },
  },
  serviceOps: {
    1: {
      title: 'Operational Prompting for IT Service Management',
      titleDE: 'Operatives Prompting für IT-Service-Management',
      subtitle: 'ITSM is service design, delivery, support, change, problem, knowledge, configuration, capacity, availability, suppliers, measurement, and continual improvement. Tickets are merely one record type.',
      subtitleDE: 'ITSM umfasst Service Design, Bereitstellung, Support, Change, Problem, Knowledge, Configuration, Capacity, Availability, Lieferanten, Messung und kontinuierliche Verbesserung. Tickets sind nur eine Form der Dokumentation.',
    },
    2: {
      title: 'ITSM Is More Than a Ticket Queue',
      titleDE: 'ITSM ist mehr als eine Ticket-Warteschlange',
      subtitle: 'The objective is service value and controlled decisions, not producing increasingly elaborate ticket prose.',
      subtitleDE: 'Das Ziel sind Service-Wert und kontrollierte Entscheidungen, nicht immer aufwendigere Ticket-Prosa.',
      technique: 'Service-value prompting',
      techniqueDE: 'Service-Value-Prompting',
      codeStandard: 'Please create a very comprehensive and polished ITSM ticket report. Include lots of detail about all tickets, explain every category, make it suitable for management, add recommendations, cover risks, trends, customer satisfaction, team performance, and everything else that might be useful. Be thorough and professional.',
      codeStandardDE: 'Bitte erstelle einen sehr umfassenden und professionellen ITSM-Ticketbericht. Füge viele Details zu allen Tickets ein, erkläre jede Kategorie, mache ihn managementtauglich, ergänze Empfehlungen und decke Risiken, Trends, Kundenzufriedenheit, Teamleistung sowie alles weitere Nützliche ab. Sei gründlich und professionell.',
      codeOptimized: 'Using the monthly service data, identify the two largest threats to payroll-service availability. Separate incidents from recurring problems, cite the supporting measures, and propose one measurable improvement experiment. Do not use ticket volume as a proxy for service quality.',
      codeOptimizedDE: 'Identifiziere anhand der monatlichen Service-Daten die zwei größten Risiken für die Verfügbarkeit des Payroll-Services. Trenne Incidents von wiederkehrenden Problems, belege Aussagen mit Kennzahlen und schlage ein messbares Verbesserungs-Experiment vor. Ticketmenge nicht als Ersatzkennzahl für Service-Qualität verwenden.',
      content: 'The shorter request manages a service outcome. The longer request manages document production. Both can produce text; only one helps manage the service.',
      contentDE: 'Der kürzere Request steuert ein Service-Ergebnis. Der längere Request steuert Dokumentproduktion. Beide erzeugen Text, aber nur einer hilft beim Management des Services.',
    },
    4: {
      title: 'Use a Service Contract, Not a Ticket Template',
      titleDE: 'Nutze einen Service-Vertrag, keine Ticket-Schablone',
      subtitle: 'Choose only the fields required for the decision, analysis, handoff, or improvement task.',
      subtitleDE: 'Wähle nur die Felder, die für Entscheidung, Analyse, Übergabe oder Verbesserung benötigt werden.',
      content: [
        'Outcome: Which service result, decision, or improvement is needed?',
        'Evidence: Which measures, events, records, policies, service maps, configuration data, or observations are available?',
        'Boundaries: What must not be invented, approved, changed, closed, or treated as fact?',
        'Method: Is this incident support, problem analysis, change readiness, capacity planning, supplier review, or knowledge work?',
        'Validation: Which service measure or evidence proves the output is useful?',
        'Handoff and write-back: Who uses the result, and which operational record should improve?',
      ],
      contentDE: [
        'Ergebnis: Welches Service-Ergebnis, welche Entscheidung oder Verbesserung wird benötigt?',
        'Evidenz: Welche Kennzahlen, Events, Records, Policies, Service Maps, Konfigurationsdaten oder Beobachtungen liegen vor?',
        'Grenzen: Was darf nicht erfunden, genehmigt, geändert, geschlossen oder als Fakt behandelt werden?',
        'Methode: Geht es um Incident Support, Problem-Analyse, Change Readiness, Capacity Planning, Supplier Review oder Knowledge Work?',
        'Validierung: Welche Service-Kennzahl oder Evidenz beweist, dass die Ausgabe nützlich ist?',
        'Übergabe und Write-back: Wer nutzt das Ergebnis und welcher operative Record muss besser werden?',
      ],
    },
    7: {
      title: 'Service Facts Require More Than Ticket Text',
      titleDE: 'Service-Fakten brauchen mehr als Tickettext',
      subtitle: 'Service maps, monitoring, configuration data, ownership, policy, and expected state bound what can be concluded.',
      subtitleDE: 'Service Maps, Monitoring, Konfigurationsdaten, Ownership, Policy und Sollzustand begrenzen, was geschlossen werden kann.',
      technique: 'Service-context retrieval',
      techniqueDE: 'Service-Kontext-Retrieval',
      codeStandard: 'Read the incident tickets and tell us why the invoice service is unreliable.',
      codeStandardDE: 'Lies die Incident-Tickets und sage uns, warum der Invoice-Service unzuverlässig ist.',
      codeOptimized: 'Compare the incident records with the service map, monitoring history, recent changes, dependency health, and known errors. Separate observed patterns from root-cause hypotheses. Return missing evidence before recommending a problem record or change.',
      codeOptimizedDE: 'Vergleiche die Incident-Records mit Service Map, Monitoring-Historie, letzten Changes, Abhängigkeitszustand und Known Errors. Trenne beobachtete Muster von Root-Cause-Hypothesen. Nenne fehlende Evidenz, bevor ein Problem Record oder Change empfohlen wird.',
      content: 'Tickets describe reported work. They rarely contain the complete service reality. Retrieval must cross the records and systems that define the service.',
      contentDE: 'Tickets beschreiben gemeldete Arbeit. Sie enthalten selten die vollständige Service-Realität. Retrieval muss die Records und Systeme verbinden, die den Service definieren.',
    },
    8: {
      title: 'Capacity and Availability Need Reproducible Analysis',
      titleDE: 'Capacity und Availability brauchen reproduzierbare Analyse',
      subtitle: 'Operational decisions need data and calculation, not a longer narrative.',
      subtitleDE: 'Operative Entscheidungen brauchen Daten und Berechnung, keine längere Erzählung.',
      technique: 'Measure-backed analysis',
      techniqueDE: 'Kennzahlenbasierte Analyse',
      codeStandard: 'Write a detailed assessment of whether the platform has enough capacity for the autumn campaign.',
      codeStandardDE: 'Schreibe eine detaillierte Bewertung, ob die Plattform genug Kapazität für die Herbstkampagne hat.',
      codeOptimized: 'Using the attached demand forecast, utilisation history, error budget, and scaling limits, calculate headroom for the autumn campaign. Show assumptions and three scenarios. Mark which missing data prevents a go/no-go recommendation.',
      codeOptimizedDE: 'Berechne anhand von Demand Forecast, Auslastungshistorie, Error Budget und Scaling-Grenzen den Headroom für die Herbstkampagne. Zeige Annahmen und drei Szenarien. Markiere, welche fehlenden Daten eine Go/No-Go-Empfehlung verhindern.',
      content: 'Capacity and availability management are ITSM work. Their outputs may become plans, thresholds, budgets, risks, or changes, not merely ticket comments.',
      contentDE: 'Capacity- und Availability-Management sind ITSM-Arbeit. Ihre Ergebnisse können Pläne, Schwellenwerte, Budgets, Risiken oder Changes werden, nicht nur Ticket-Kommentare.',
    },
    9: {
      title: 'Handoffs Must Carry Service Context',
      titleDE: 'Übergaben müssen Service-Kontext transportieren',
      subtitle: 'A handoff is useful when the next role receives evidence, impact, ownership, decision need, and open risks.',
      subtitleDE: 'Eine Übergabe ist nützlich, wenn die nächste Rolle Evidenz, Impact, Ownership, Entscheidungsbedarf und offene Risiken erhält.',
      content: 'Structured output is not limited to escalation tickets. It supports change advisory, supplier review, architecture decisions, service reviews, problem investigation, and operational handoffs.',
      contentDE: 'Strukturierte Ausgabe ist nicht auf Eskalationstickets begrenzt. Sie unterstützt Change Advisory, Supplier Review, Architekturentscheidungen, Service Reviews, Problem-Untersuchung und operative Übergaben.',
    },
    12: {
      title: 'Resolved Work Must Improve the Service System',
      titleDE: 'Gelöste Arbeit muss das Service-System verbessern',
      subtitle: 'Write-back can update knowledge, known errors, monitoring, configuration records, policies, ownership, measures, and improvement backlogs.',
      subtitleDE: 'Write-back kann Knowledge, Known Errors, Monitoring, Configuration Records, Policies, Ownership, Kennzahlen und Verbesserungs-Backlogs aktualisieren.',
      technique: 'Problem and knowledge write-back',
      techniqueDE: 'Problem- und Knowledge-Write-back',
      content: 'A KB article is only one possible result. Repeated incidents may require a problem record, changed alert, updated service map, corrected ownership, improved recovery control, or a funded improvement item.',
      contentDE: 'Ein KB-Artikel ist nur ein mögliches Ergebnis. Wiederkehrende Incidents können einen Problem Record, geänderten Alert, aktualisierte Service Map, korrigierte Ownership, bessere Recovery-Kontrolle oder ein finanziertes Improvement Item erfordern.',
    },
    13: {
      title: 'IT Service Management Control Loop',
      titleDE: 'IT-Service-Management-Kontrollschleife',
      subtitle: 'Outcome → Evidence → Boundaries → Analysis → Decision → Validation → Handoff → Improvement.',
      subtitleDE: 'Ergebnis → Evidenz → Grenzen → Analyse → Entscheidung → Validierung → Übergabe → Verbesserung.',
      content: [
        'Outcome: Which user, business, or service result matters?',
        'Evidence: Which service measures, events, records, dependencies, policies, and observations support the work?',
        'Boundaries: What may the LLM prepare, and what still requires an accountable human or approved tool?',
        'Analysis: Is the task incident, request, problem, change, knowledge, capacity, availability, supplier, configuration, or continual-improvement work?',
        'Decision and validation: What decision is needed, and what evidence proves it is safe or useful?',
        'Handoff and improvement: Who acts next, and what should change in the service-management system?',
      ],
      contentDE: [
        'Ergebnis: Welches Nutzer-, Business- oder Service-Ergebnis zählt?',
        'Evidenz: Welche Service-Kennzahlen, Events, Records, Abhängigkeiten, Policies und Beobachtungen stützen die Arbeit?',
        'Grenzen: Was darf das LLM vorbereiten und was erfordert weiterhin einen verantwortlichen Menschen oder ein genehmigtes Tool?',
        'Analyse: Geht es um Incident, Request, Problem, Change, Knowledge, Capacity, Availability, Supplier, Configuration oder Continual Improvement?',
        'Entscheidung und Validierung: Welche Entscheidung wird benötigt und welche Evidenz beweist Sicherheit oder Nutzen?',
        'Übergabe und Verbesserung: Wer handelt als Nächstes und was muss sich im Service-Management-System ändern?',
      ],
    },
    14: {
      subtitle: 'The LLM should prepare controlled service-management work, not produce longer tickets or pretend it operated the service.',
      subtitleDE: 'Das LLM soll kontrollierte Service-Management-Arbeit vorbereiten, nicht längere Tickets erzeugen oder so tun, als hätte es den Service betrieben.',
      content: [
        'ITSM manages service value, risk, capability, knowledge, and improvement across the service lifecycle. Ticket handling is only one activity.',
        'Good prompts are task-fit: concise for simple preparation, explicit for risky decisions, and evidence-heavy where service impact matters.',
        'The model may analyse provided evidence, expose gaps, draft decisions and handoffs, and prepare write-back. Accountable people and approved systems still perform and authorize the work.',
      ],
      contentDE: [
        'ITSM steuert Service-Wert, Risiko, Fähigkeiten, Wissen und Verbesserung über den Service-Lebenszyklus. Ticketbearbeitung ist nur eine Aktivität.',
        'Gute Prompts passen zur Aufgabe: knapp bei einfacher Vorbereitung, explizit bei riskanten Entscheidungen und evidenzstark bei relevantem Service-Impact.',
        'Das Modell darf bereitgestellte Evidenz analysieren, Lücken zeigen, Entscheidungen und Übergaben entwerfen sowie Write-back vorbereiten. Verantwortliche Menschen und genehmigte Systeme führen die Arbeit weiterhin aus und autorisieren sie.',
      ],
    },
  },
};

const applyOverrides = (mode: GuideMode): SlideData[] => BASE_GUIDE_SLIDES[mode].map((slide) => ({
  ...slide,
  ...OVERRIDES[mode][slide.id],
}));

export const GUIDE_SLIDES: Record<GuideMode, SlideData[]> = {
  coding: applyOverrides('coding'),
  serviceOps: applyOverrides('serviceOps'),
};
